import { useState } from 'react';
import type { FormEvent } from 'react';
import { Link, useParams } from 'react-router-dom';
import { catalogApi } from '../api/catalog';
import { useInventoryAuth } from '../auth/useInventoryAuth';
import type { Ingredient, MappingWrite, Supplier, SupplierIngredient, SupplierWrite } from '../types/catalog';
import { Badge, ConfirmDialog, EmptyState, ErrorPanel, Field, LoadingState, Modal, PageHeader, Panel } from '../components/ui';
import { useQuery } from '../hooks/useQuery';
import { useMutation } from '../hooks/useMutation';
import { useUnsavedChanges } from '../hooks/useUnsavedChanges';
import { dateTime, money, normalizeDecimal, quantity } from '../utils/format';
import { ActiveFilter, CatalogResult, CatalogSearch, DecimalField, FormActions, IngredientPicker, UnitSelect } from './CatalogShared';
import { decimalError, useCatalogFilters, useUnitOptions } from './CatalogHelpers';

export function SuppliersPage() {
  const { can } = useInventoryAuth();
  const filter = useCatalogFilters();
  const query = useQuery(`suppliers:${JSON.stringify(filter.query)}`, signal => catalogApi.suppliers(filter.query, signal));
  const [editor, setEditor] = useState<Supplier | 'new' | null>(null);
  const [deactivate, setDeactivate] = useState<Supplier | null>(null);
  const mutation = useMutation();
  const add = can('manageSuppliers') ? <button className="inv-button" onClick={() => setEditor('new')}>Thêm nhà cung cấp</button> : undefined;
  return <><PageHeader title="Nhà cung cấp" description="Thông tin liên hệ và danh mục nguyên liệu phục vụ mua hàng." actions={add} /><Panel><div className="inv-form-grid"><CatalogSearch maxLength={180} value={filter.search} onChange={value => filter.setFilter('search', value)} placeholder="Mã, tên, người liên hệ, điện thoại hoặc email" /><ActiveFilter value={filter.status} onChange={value => filter.setFilter('status', value)} suspended /><button className="inv-button secondary" onClick={filter.clear}>Xóa bộ lọc</button></div></Panel>
    <CatalogResult query={query} page={filter.page} onPage={page => filter.setFilter('page', String(page))} empty={<EmptyState title={filter.search || filter.status ? 'Không tìm thấy nhà cung cấp phù hợp' : 'Chưa có nhà cung cấp'} action={filter.search || filter.status ? <button className="inv-button secondary" onClick={filter.clear}>Xóa bộ lọc</button> : add} />}>{data => <div className="inv-table-wrap"><table className="inv-table"><caption>Danh sách nhà cung cấp</caption><thead><tr><th>Nhà cung cấp</th><th>Người liên hệ</th><th>Điện thoại / email</th><th>Trạng thái</th><th>Thao tác</th></tr></thead><tbody>{data.items.map(item => <tr key={item.supplier_id}><td><Link className="inv-link" to={`/inventory/suppliers/${item.supplier_id}`}>{item.supplier_name}</Link><div className="inv-code inv-muted">{item.supplier_code}</div></td><td>{item.contact_name || '—'}</td><td>{item.phone || '—'}<div className="inv-muted">{item.email}</div></td><td><Badge status={item.status} /></td><td>{can('manageSuppliers') && <div className="inv-actions"><button className="inv-button secondary" onClick={() => setEditor(item)}>Sửa</button>{item.status !== 'INACTIVE' && <button className="inv-button secondary" onClick={() => { mutation.clearError(); setDeactivate(item); }}>Ngừng hợp tác</button>}</div>}</td></tr>)}</tbody></table></div>}</CatalogResult>
    {can('manageSuppliers') && editor && <SupplierForm supplier={editor === 'new' ? undefined : editor} onClose={() => setEditor(null)} onSaved={() => { setEditor(null); query.refresh(); }} />}
    <ConfirmDialog open={can('manageSuppliers') && !!deactivate} title="Ngừng hợp tác với nhà cung cấp?" pending={mutation.pending} onClose={() => setDeactivate(null)} onConfirm={() => { if (can('manageSuppliers') && deactivate) void mutation.run(() => catalogApi.deactivateSupplier(deactivate.supplier_id), () => { setDeactivate(null); query.refresh(); }); }}><p>{deactivate?.supplier_name} và toàn bộ liên kết nguyên liệu của họ sẽ ngừng hoạt động; ưu tiên cung cấp được gỡ bỏ. Lịch sử đơn mua được giữ nguyên. Kích hoạt lại nhà cung cấp không tự mở lại các liên kết.</p>{mutation.error && <ErrorPanel error={mutation.error} />}</ConfirmDialog>
  </>;
}

function SupplierForm({ supplier, onClose, onSaved }: { supplier?: Supplier; onClose: () => void; onSaved: () => void }) {
  const { can } = useInventoryAuth();
  const initial: SupplierWrite = supplier ? { supplier_code: supplier.supplier_code, supplier_name: supplier.supplier_name, status: supplier.status, contact_name: supplier.contact_name, phone: supplier.phone, email: supplier.email, address: supplier.address, tax_code: supplier.tax_code } : { supplier_code: '', supplier_name: '', status: 'ACTIVE', contact_name: null, phone: null, email: null, address: null, tax_code: null };
  const [form, setForm] = useState(initial); const [confirmInactive, setConfirmInactive] = useState(false);
  const mutation = useMutation(); const dirty = JSON.stringify(form) !== JSON.stringify(initial); useUnsavedChanges(dirty);
  const close = () => { if (!mutation.pending && (!dirty || window.confirm('Bỏ các thay đổi nhà cung cấp chưa lưu?'))) onClose(); };
  const change = <K extends keyof SupplierWrite>(key: K, value: SupplierWrite[K]) => setForm(current => ({ ...current, [key]: value }));
  function save() { if (!can('manageSuppliers')) return; void mutation.run(() => catalogApi.saveSupplier({ ...form, supplier_code: form.supplier_code.trim(), supplier_name: form.supplier_name.trim() }, supplier?.supplier_id), onSaved); }
  function submit(event: FormEvent) { event.preventDefault(); if (!can('manageSuppliers')) return; if (supplier && supplier.status !== 'INACTIVE' && form.status === 'INACTIVE') setConfirmInactive(true); else save(); }
  return <Modal title={supplier ? 'Sửa nhà cung cấp' : 'Thêm nhà cung cấp'} open onClose={close}><form onSubmit={submit}><div className="inv-form-grid"><Field label="Mã nhà cung cấp"><input autoFocus required pattern=".*\S.*" maxLength={40} value={form.supplier_code} onChange={event => change('supplier_code', event.target.value)} /></Field><Field label="Tên nhà cung cấp"><input required pattern=".*\S.*" maxLength={180} value={form.supplier_name} onChange={event => change('supplier_name', event.target.value)} /></Field><Field label="Người liên hệ"><input maxLength={120} value={form.contact_name ?? ''} onChange={event => change('contact_name', event.target.value || null)} /></Field><Field label="Số điện thoại"><input type="tel" maxLength={20} value={form.phone ?? ''} onChange={event => change('phone', event.target.value || null)} /></Field><Field label="Email"><input type="email" maxLength={150} value={form.email ?? ''} onChange={event => change('email', event.target.value || null)} /></Field><Field label="Mã số thuế"><input maxLength={30} value={form.tax_code ?? ''} onChange={event => change('tax_code', event.target.value || null)} /></Field><Field label="Trạng thái"><select value={form.status} onChange={event => change('status', event.target.value as SupplierWrite['status'])}><option value="ACTIVE">Đang hoạt động</option><option value="SUSPENDED">Tạm ngưng</option><option value="INACTIVE">Ngừng hoạt động</option></select></Field><Field label="Địa chỉ"><textarea value={form.address ?? ''} onChange={event => change('address', event.target.value || null)} /></Field></div>{mutation.error && <ErrorPanel error={mutation.error} />}<FormActions pending={mutation.pending} onClose={close} /></form><ConfirmDialog open={confirmInactive} title="Ngừng toàn bộ danh mục cung cấp?" pending={mutation.pending} onClose={() => setConfirmInactive(false)} onConfirm={save}><p>Ngừng nhà cung cấp cũng ngừng mọi liên kết nguyên liệu và gỡ ưu tiên. Kích hoạt lại sau này cần mở lại từng liên kết.</p>{mutation.error && <ErrorPanel error={mutation.error} />}</ConfirmDialog></Modal>;
}

export function SupplierDetailPage() {
  const { can } = useInventoryAuth();
  const { id } = useParams(); const supplierId = Number(id);
  const query = useQuery(`supplier:${id}`, signal => catalogApi.supplier(supplierId, signal));
  const [editing, setEditing] = useState(false);
  if (query.loading && !query.data) return <LoadingState />;
  if (query.error) return <ErrorPanel error={query.error} onRetry={query.refresh} />;
  const supplier = query.data; if (!supplier) return null;
  return <><PageHeader title={supplier.supplier_name} description={supplier.supplier_code} actions={<div className="inv-actions">{can('manageSuppliers') && <button className="inv-button secondary" onClick={() => setEditing(true)}>Sửa thông tin</button>}{can('viewPurchaseOrders') && <Link className="inv-button" to={`/inventory/purchase-orders?supplier_id=${supplier.supplier_id}`}>Xem đơn mua</Link>}</div>} /><Panel title="Thông tin liên hệ"><dl className="inv-summary"><div><dt>Trạng thái</dt><dd><Badge status={supplier.status} /></dd></div><div><dt>Người liên hệ</dt><dd>{supplier.contact_name || '—'}</dd></div><div><dt>Điện thoại</dt><dd>{supplier.phone || '—'}</dd></div><div><dt>Email</dt><dd>{supplier.email || '—'}</dd></div><div><dt>Mã số thuế</dt><dd>{supplier.tax_code || '—'}</dd></div><div><dt>Địa chỉ</dt><dd>{supplier.address || '—'}</dd></div><div><dt>Cập nhật</dt><dd>{dateTime(supplier.updated_at)}</dd></div></dl></Panel><SupplierMappings supplier={supplier} />{can('manageSuppliers') && editing && <SupplierForm supplier={supplier} onClose={() => setEditing(false)} onSaved={() => { setEditing(false); query.refresh(); }} />}</>;
}

function SupplierMappings({ supplier }: { supplier: Supplier }) {
  const { can } = useInventoryAuth();
  const units = useUnitOptions();
  const [page, setPage] = useState(1); const [active, setActive] = useState('');
  const query = useQuery(`supplier-mappings:${supplier.supplier_id}:${page}:${active}`, signal => catalogApi.mappings({ supplier_id: supplier.supplier_id, page, is_active: active === '' ? undefined : active === 'true' }, signal));
  const [editor, setEditor] = useState<SupplierIngredient | 'new' | null>(null);
  const [action, setAction] = useState<{ row: SupplierIngredient; type: 'deactivate' | 'preferred' } | null>(null);
  const mutation = useMutation();
  const add = can('manageSuppliers') && supplier.status === 'ACTIVE' ? <button className="inv-button" onClick={() => setEditor('new')}>Thêm nguyên liệu cung cấp</button> : undefined;
  return <Panel title="Danh mục nguyên liệu cung cấp" actions={add}>{units.error && <ErrorPanel error={units.error} onRetry={units.refresh} />}<Field label="Trạng thái liên kết"><select value={active} onChange={event => { setActive(event.target.value); setPage(1); }}><option value="">Tất cả liên kết</option><option value="true">Đang hoạt động</option><option value="false">Ngừng hoạt động</option></select></Field><CatalogResult query={query} page={page} onPage={setPage} empty={<EmptyState title="Chưa có liên kết phù hợp" action={add} />}>{data => <div className="inv-table-wrap"><table className="inv-table"><caption>Đơn vị mua, định mức và giá của nhà cung cấp</caption><thead><tr><th>Nguyên liệu</th><th>Quy cách mua</th><th>Đặt tối thiểu</th><th>Giá gần nhất</th><th>Giao hàng</th><th>Ưu tiên / trạng thái</th><th>Thao tác</th></tr></thead><tbody>{data.items.map(row => <tr key={row.supplier_ingredient_id}><td>{can('viewIngredients') ? <Link className="inv-link" to={`/inventory/ingredients/${row.ingredient_id}`}>{row.ingredient.ingredient_name}</Link> : row.ingredient.ingredient_name}<div className="inv-muted">{row.supplier_sku || row.ingredient.ingredient_code}</div></td><td>1 {row.purchase_unit.unit_code} = {quantity(row.base_qty_per_purchase_unit)} {units.data?.find(unit => unit.unit_id === row.ingredient.base_unit_id)?.unit_code ?? `#${row.ingredient.base_unit_id}`}</td><td>{quantity(row.minimum_order_qty)} {row.purchase_unit.unit_code}</td><td>{row.latest_unit_price === null ? 'Chưa có giá' : money(row.latest_unit_price)}<div className="inv-muted">/ {row.purchase_unit.unit_code}</div></td><td>{row.lead_time_days} ngày</td><td>{row.is_preferred && <div>Nhà cung cấp ưu tiên</div>}<Badge status={row.is_active ? 'ACTIVE' : 'INACTIVE'} /></td><td>{can('manageSuppliers') && <div className="inv-actions"><button className="inv-button secondary" onClick={() => setEditor(row)}>Sửa</button>{row.is_active && !row.is_preferred && supplier.status === 'ACTIVE' && <button className="inv-button secondary" onClick={() => { mutation.clearError(); setAction({ row, type: 'preferred' }); }}>Ưu tiên</button>}{row.is_active && <button className="inv-button secondary" onClick={() => { mutation.clearError(); setAction({ row, type: 'deactivate' }); }}>Ngừng cung cấp</button>}</div>}</td></tr>)}</tbody></table></div>}</CatalogResult>
    {can('manageSuppliers') && editor && <MappingForm supplier={supplier} mapping={editor === 'new' ? undefined : editor} onClose={() => setEditor(null)} onSaved={() => { setEditor(null); query.refresh(); }} />}
    <ConfirmDialog open={can('manageSuppliers') && !!action} title={action?.type === 'preferred' ? 'Chọn nhà cung cấp ưu tiên?' : 'Ngừng liên kết nguyên liệu?'} pending={mutation.pending} onClose={() => setAction(null)} onConfirm={() => { if (can('manageSuppliers') && action) void mutation.run(async () => { if (action.type === 'preferred') await catalogApi.updateMapping(action.row.supplier_ingredient_id, { is_preferred: true }); else await catalogApi.deactivateMapping(action.row.supplier_ingredient_id); }, () => { setAction(null); query.refresh(); }); }}><p>{action?.type === 'preferred' ? `${supplier.supplier_name} sẽ là nhà cung cấp ưu tiên cho ${action.row.ingredient.ingredient_name}. Ưu tiên của nhà cung cấp khác cho cùng nguyên liệu sẽ được gỡ trong cùng giao dịch.` : 'Liên kết ngừng hoạt động và được gỡ ưu tiên. Đơn mua trước đây giữ nguyên thông tin.'}</p>{mutation.error && <ErrorPanel error={mutation.error} />}</ConfirmDialog>
  </Panel>;
}

function MappingForm({ supplier, mapping, onClose, onSaved }: { supplier: Supplier; mapping?: SupplierIngredient; onClose: () => void; onSaved: () => void }) {
  const { can } = useInventoryAuth();
  const initial: MappingWrite = mapping ? { supplier_id: supplier.supplier_id, ingredient_id: mapping.ingredient_id, supplier_sku: mapping.supplier_sku, purchase_unit_id: mapping.purchase_unit_id, base_qty_per_purchase_unit: mapping.base_qty_per_purchase_unit, lead_time_days: mapping.lead_time_days, minimum_order_qty: mapping.minimum_order_qty, latest_unit_price: mapping.latest_unit_price, is_preferred: mapping.is_preferred, is_active: mapping.is_active } : { supplier_id: supplier.supplier_id, ingredient_id: 0, supplier_sku: null, purchase_unit_id: 0, base_qty_per_purchase_unit: '', lead_time_days: 0, minimum_order_qty: '1', latest_unit_price: null, is_preferred: false, is_active: true };
  const [form, setForm] = useState(initial); const [ingredient, setIngredient] = useState<Ingredient>(); const [attempted, setAttempted] = useState(false); const [confirmPreferred, setConfirmPreferred] = useState(false);
  const units = useUnitOptions(); const mutation = useMutation(); const dirty = JSON.stringify(form) !== JSON.stringify(initial); useUnsavedChanges(dirty);
  const change = <K extends keyof MappingWrite>(key: K, value: MappingWrite[K]) => setForm(current => ({ ...current, [key]: value }));
  const close = () => { if (!mutation.pending && (!dirty || window.confirm('Bỏ liên kết nguyên liệu chưa lưu?'))) onClose(); };
  const baseUnit = units.data?.find(unit => unit.unit_id === (ingredient?.base_unit_id ?? mapping?.ingredient.base_unit_id));
  const purchaseUnit = units.data?.find(unit => unit.unit_id === form.purchase_unit_id);
  function save() {
    if (!can('manageSuppliers')) return;
    const payload: MappingWrite = { ...form, base_qty_per_purchase_unit: normalizeDecimal(form.base_qty_per_purchase_unit), minimum_order_qty: normalizeDecimal(form.minimum_order_qty), latest_unit_price: form.latest_unit_price === null ? null : normalizeDecimal(form.latest_unit_price), is_preferred: form.is_active && form.is_preferred };
    const update = { supplier_sku: payload.supplier_sku, purchase_unit_id: payload.purchase_unit_id, base_qty_per_purchase_unit: payload.base_qty_per_purchase_unit, lead_time_days: payload.lead_time_days, minimum_order_qty: payload.minimum_order_qty, latest_unit_price: payload.latest_unit_price, is_preferred: payload.is_preferred, is_active: payload.is_active };
    void mutation.run(() => mapping ? catalogApi.updateMapping(mapping.supplier_ingredient_id, update) : catalogApi.createMapping(payload), onSaved);
  }
  function submit(event: FormEvent) { event.preventDefault(); if (!can('manageSuppliers')) return; setAttempted(true); if (!form.ingredient_id || decimalError(form.base_qty_per_purchase_unit, 3, true) || decimalError(form.minimum_order_qty, 3, true) || (form.latest_unit_price !== null && decimalError(form.latest_unit_price, 2))) return; if (form.is_active && form.is_preferred && !mapping?.is_preferred) setConfirmPreferred(true); else save(); }
  return <Modal title={mapping ? 'Sửa nguyên liệu cung cấp' : 'Thêm nguyên liệu cung cấp'} open onClose={close}><form onSubmit={submit}>
    {mapping ? <p><strong>{mapping.ingredient.ingredient_name}</strong> · {mapping.ingredient.ingredient_code}</p> : <><IngredientPicker onPick={item => { setIngredient(item); setForm(current => ({ ...current, ingredient_id: item.ingredient_id, purchase_unit_id: item.base_unit_id, base_qty_per_purchase_unit: '1' })); }} />{ingredient && <p>Đã chọn: <strong>{ingredient.ingredient_name}</strong> · {ingredient.ingredient_code}</p>}{attempted && !form.ingredient_id && <p role="alert">Vui lòng chọn nguyên liệu.</p>}</>}
    <div className="inv-form-grid"><UnitSelect label="Đơn vị mua" units={units.data ?? []} value={form.purchase_unit_id} onChange={value => change('purchase_unit_id', value)} /><DecimalField label={`Số ${baseUnit?.unit_code ?? 'đơn vị cơ sở'} trong 1 đơn vị mua`} value={form.base_qty_per_purchase_unit} onChange={value => change('base_qty_per_purchase_unit', value)} attempted={attempted} positive /><DecimalField label="Số lượng đặt tối thiểu (đơn vị mua)" value={form.minimum_order_qty} onChange={value => change('minimum_order_qty', value)} attempted={attempted} positive /><Field label="Giá gần nhất / đơn vị mua (VND, không bắt buộc)" error={attempted && form.latest_unit_price !== null ? decimalError(form.latest_unit_price, 2) : undefined}><input inputMode="decimal" value={form.latest_unit_price ?? ''} onChange={event => change('latest_unit_price', event.target.value === '' ? null : event.target.value)} /></Field><Field label="Thời gian giao hàng (ngày)"><input type="number" min={0} max={2147483647} step={1} required value={form.lead_time_days} onChange={event => change('lead_time_days', Number(event.target.value))} /></Field><Field label="Mã nguyên liệu phía nhà cung cấp"><input maxLength={80} value={form.supplier_sku ?? ''} onChange={event => change('supplier_sku', event.target.value || null)} /></Field><Field label="Liên kết đang hoạt động"><input type="checkbox" checked={form.is_active} disabled={supplier.status !== 'ACTIVE' && !form.is_active} onChange={event => change('is_active', event.target.checked)} /></Field><Field label="Nhà cung cấp ưu tiên"><input type="checkbox" checked={form.is_preferred && form.is_active} disabled={!form.is_active || supplier.status !== 'ACTIVE'} onChange={event => change('is_preferred', event.target.checked)} /></Field></div>
    {purchaseUnit && baseUnit && !decimalError(form.base_qty_per_purchase_unit, 3, true) && <p className="inv-summary">1 {purchaseUnit.unit_code} = {quantity(normalizeDecimal(form.base_qty_per_purchase_unit))} {baseUnit.unit_code}</p>}{units.error && <ErrorPanel error={units.error} onRetry={units.refresh} />}{mutation.error && <ErrorPanel error={mutation.error} />}<FormActions pending={mutation.pending || units.loading} onClose={close} /></form><ConfirmDialog open={confirmPreferred} title="Thay đổi nhà cung cấp ưu tiên?" pending={mutation.pending} onClose={() => setConfirmPreferred(false)} onConfirm={save}><p>Ưu tiên của nhà cung cấp khác cho nguyên liệu này sẽ được gỡ bỏ khi lưu.</p>{mutation.error && <ErrorPanel error={mutation.error} />}</ConfirmDialog></Modal>;
}
