import { useState } from 'react';
import { Link, useParams, useSearchParams } from 'react-router-dom';
import { get } from '../api/http';
import { stockLabels, stockSnapshot, type Lot, type Movement } from '../api/stock';
import type { Page } from '../types/common';
import type { Ingredient } from '../types/catalog';
import { Badge, EmptyState, ErrorPanel, Field, LoadingState, PageHeader, Pagination, Panel } from '../components/ui';
import { useQuery } from '../hooks/useQuery';
import { compareDecimal, date, dateTime, expiryDays, expiryStatus, money, multiplyDecimal, quantity, subtractDecimal } from '../utils/format';
import { downloadCsv } from '../utils/csv';
import { CatalogSearch } from './CatalogShared';
import { stockHealth, movementLabel } from '../utils/stock';
import { useInventoryAuth } from '../auth/useInventoryAuth';

export function StockPage() {
  const { can } = useInventoryAuth();
  const [params, setParams] = useSearchParams();
  const query = useQuery('stock:snapshot', stockSnapshot);
  const page = Math.max(1, Number(params.get('page')) || 1);
  const search = params.get('search') ?? ''; const status = params.get('health') ?? '';
  const set = (key: string, value: string) => setParams(previous => { const next = new URLSearchParams(previous); if (value) next.set(key, value); else next.delete(key); if (key !== 'page') next.delete('page'); return next; }, { replace: true });
  const data = query.data;
  const ingredients = new Map(data?.ingredients.map(item => [item.ingredient_id, item]));
  const rows = (data?.balances ?? []).filter(row => {
    const ingredient = ingredients.get(row.ingredient_id);
    const lots = data?.lots.filter(lot => lot.ingredient_id === row.ingredient_id && compareDecimal(lot.current_quantity, '0') > 0) ?? [];
    return (!params.get('ingredient_id') || String(row.ingredient_id) === params.get('ingredient_id')) && `${row.ingredient_code} ${row.ingredient_name}`.toLocaleLowerCase('vi').includes(search.toLocaleLowerCase('vi')) && (!status || (status === 'EXPIRING' ? lots.some(lot => { const days = expiryDays(lot.expiry_date); return days !== null && days >= 0 && days <= 14; }) : status === 'EXPIRED' ? lots.some(lot => expiryStatus(lot.expiry_date) === 'EXPIRED' || lot.status === 'EXPIRED') : stockHealth(row, ingredient) === status)) && (!params.get('unit_id') || String(row.base_unit_id) === params.get('unit_id')) && (!params.get('status') || ingredient?.status === params.get('status'));
  });
  const units = [...new Map(data?.ingredients.map(item => [item.base_unit_id, item.base_unit])).values()];
  return <><PageHeader title="Tồn kho hiện tại" description="Đối chiếu tồn thực tế, tồn khả dụng và phần chưa thể cấp xuất." actions={<>{can('createStocktakes') && <Link className="inv-button secondary" to="/inventory/stocktakes/new">Tạo kiểm kê</Link>}{(can('issueStock') || can('adjustStock')) && <Link className="inv-button" to="/inventory/adjustments/new">Xuất / điều chỉnh</Link>}</>} />
    <Panel><div className="inv-toolbar"><CatalogSearch value={search} onChange={value => set('search', value)} /><Field label="Tình trạng tồn"><select value={status} onChange={e => set('health', e.target.value)}><option value="">Tất cả</option><option value="OUT_OF_STOCK">Hết tồn khả dụng</option><option value="LOW">Dưới định mức</option><option value="HEALTHY">Đủ định mức</option><option value="EXPIRING">Có lô cận hạn</option><option value="EXPIRED">Có lô hết hạn</option></select></Field><Field label="Đơn vị"><select value={params.get('unit_id') ?? ''} onChange={e => set('unit_id', e.target.value)}><option value="">Tất cả đơn vị</option>{units.map(unit => <option key={unit.unit_id} value={unit.unit_id}>{unit.unit_code}</option>)}</select></Field><Field label="Nguyên liệu"><select value={params.get('status') ?? ''} onChange={e => set('status', e.target.value)}><option value="">Tất cả</option><option value="ACTIVE">Hoạt động</option><option value="INACTIVE">Ngừng hoạt động</option></select></Field><button className="inv-button secondary" onClick={() => setParams({})}>Xóa bộ lọc</button></div>
    <p className="inv-note">Tổng tồn gồm cả lô khóa và hết hạn. Cảnh báo tồn dựa trên lượng khả dụng theo đơn vị cơ sở; mỗi dòng là một nguyên liệu.</p>
    {query.loading && <LoadingState />}{query.error && <ErrorPanel error={query.error} onRetry={query.refresh} />}{data && !query.loading && !query.error && <>{rows.length ? <div className="inv-table-wrap"><table className="inv-table"><thead><tr><th>Nguyên liệu</th><th>Tổng tồn</th><th>Khả dụng</th><th>Chưa khả dụng</th><th>Định mức tối thiểu</th><th>Lô / hạn gần nhất</th><th>Tình trạng</th><th>Thao tác</th></tr></thead><tbody>{rows.slice((page - 1) * 20, page * 20).map(row => {
      const item = ingredients.get(row.ingredient_id); const unit = item?.base_unit.unit_code ?? `ĐVT #${row.base_unit_id}`; const lots = data.lots.filter(lot => lot.ingredient_id === row.ingredient_id && compareDecimal(lot.current_quantity, '0') > 0); const closest = lots.map(lot => lot.expiry_date).filter((value): value is string => !!value).sort()[0];
      return <tr className="inv-stock-row" key={row.ingredient_id}><td data-label="Nguyên liệu"><Link className="inv-link" to={`/inventory/ingredients/${row.ingredient_id}`}>{row.ingredient_name}</Link><small className="inv-code">{row.ingredient_code}</small>{item?.status === 'INACTIVE' && <Badge status="INACTIVE" />}</td><td data-label="Tổng tồn" className="numeric">{quantity(row.current_quantity)} {unit}</td><td data-label="Khả dụng" className="numeric">{quantity(row.available_quantity)} {unit}</td><td data-label="Chưa khả dụng" className="numeric">{quantity(row.unavailable_quantity)} {unit}</td><td data-label="Tối thiểu" className="numeric">{quantity(item?.minimum_stock_qty)} {unit}</td><td data-label="Lô / hạn gần nhất"><Link to={`/inventory/lots?ingredient_id=${row.ingredient_id}`}>{lots.length} lô còn tồn</Link><small>{date(closest)}</small></td><td data-label="Tình trạng"><Badge status={stockHealth(row, item)} /></td><td data-label="Thao tác"><div className="inv-actions"><Link to={`/inventory/movements?ingredient_id=${row.ingredient_id}`}>Biến động</Link>{can('issueStock') && <Link to={`/inventory/adjustments/new?ingredient_id=${row.ingredient_id}`}>Xuất kho</Link>}</div></td></tr>;
    })}</tbody></table></div> : <EmptyState title={data.balances.length ? 'Không tìm thấy kết quả phù hợp' : 'Chưa có nguyên liệu để theo dõi tồn'} action={<Link className="inv-button" to="/inventory/ingredients">Mở danh mục nguyên liệu</Link>} />}
    <Pagination page={page} total={rows.length} pageSize={20} onChange={value => set('page', String(value))} /><div className="inv-actions"><button className="inv-button secondary" onClick={() => downloadCsv('ton-kho.csv', ['Mã', 'Nguyên liệu', 'Đơn vị', 'Tổng tồn', 'Khả dụng', 'Chưa khả dụng'], rows.map(row => [row.ingredient_code, row.ingredient_name, ingredients.get(row.ingredient_id)?.base_unit.unit_code, row.current_quantity, row.available_quantity, row.unavailable_quantity]))}>Xuất CSV ({rows.length} dòng)</button><button className="inv-button secondary" onClick={query.refresh}>Làm mới</button></div></>}
    </Panel></>;
}

function ListFilters({kind, params, setParams}: {kind: 'lots' | 'movements'; params: URLSearchParams; setParams: (params: URLSearchParams) => void}) {
  return <form className="inv-toolbar" key={params.toString()} onSubmit={event => { event.preventDefault(); const form = new FormData(event.currentTarget); const next = new URLSearchParams(); for (const [key,value] of form.entries()) if (String(value)) next.set(key,String(value)); setParams(next); }}>
    <Field label="Mã số nguyên liệu"><input type="number" name="ingredient_id" min="1" step="1" defaultValue={params.get('ingredient_id') ?? ''} placeholder="Tất cả nguyên liệu" /></Field>
    {kind === 'lots' ? <><Field label="Trạng thái lô"><select name="status" defaultValue={params.get('status') ?? ''}><option value="">Tất cả</option><option value="ACTIVE">Hoạt động</option><option value="DEPLETED">Hết lô</option><option value="EXPIRED">Hết hạn</option><option value="BLOCKED">Bị khóa</option></select></Field><Field label="Khả dụng"><select name="available_only" defaultValue={params.get('available_only') ?? ''}><option value="">Tất cả lô</option><option value="true">Chỉ lô cấp xuất được</option></select></Field></> : <><Field label="Mã số lô"><input type="number" name="stock_lot_id" min="1" step="1" defaultValue={params.get('stock_lot_id') ?? ''} /></Field><Field label="Loại biến động"><select name="movement_type" defaultValue={params.get('movement_type') ?? ''}><option value="">Tất cả</option><option value="RECEIPT">Nhập hàng</option><option value="CONSUMPTION">Tiêu hao món</option><option value="ADJUSTMENT">Điều chỉnh / xuất thủ công</option><option value="RETURN">Hoàn trả</option></select></Field><Field label="Từ ngày"><input type="date" name="from" defaultValue={params.get('from') ?? ''} /></Field><Field label="Đến ngày"><input type="date" name="to" min={params.get('from') ?? undefined} defaultValue={params.get('to') ?? ''} /></Field></>}
    <div className="inv-actions"><button className="inv-button">Lọc</button><button className="inv-button secondary" type="button" onClick={() => setParams(new URLSearchParams())}>Xóa bộ lọc</button></div>
  </form>;
}
export function LotsPage() {
  const { can } = useInventoryAuth();
  const [params, setParams] = useSearchParams(); const page = Math.max(1, Number(params.get('page')) || 1);
  const query = useQuery(`lots:${params}`, async signal => { const lots = await get<Page<Lot>>('/inventory/stock-lots', {ingredient_id: params.get('ingredient_id') || undefined, status: params.get('status') || undefined, available_only: params.get('available_only') || undefined, limit: 20, offset: (page - 1) * 20}, signal); const labels = await stockLabels(lots.items.map(lot => lot.ingredient_id), signal); return {...lots, labels}; });
  return <><PageHeader title="Lô hàng" description="Theo dõi nguồn nhập, lượng còn lại và hạn sử dụng của từng lô." actions={can('createReceipts') && <Link className="inv-button" to="/inventory/goods-receipts/new">Nhập hàng</Link>} /><Panel><ListFilters kind="lots" params={params} setParams={setParams} />{query.loading && <LoadingState />}{query.error && <ErrorPanel error={query.error} onRetry={query.refresh} />}{query.data && !query.loading && !query.error && <>{query.data.items.length ? <div className="inv-table-wrap"><table className="inv-table"><thead><tr><th>Lô / nguyên liệu</th><th>Ngày tạo</th><th>Hạn sử dụng</th><th>Nhập ban đầu</th><th>Còn lại</th><th>Giá trị còn lại</th><th>Trạng thái</th></tr></thead><tbody>{query.data.items.map(lot => { const item = query.data!.labels[lot.ingredient_id]; const days = expiryDays(lot.expiry_date); return <tr key={lot.stock_lot_id}><td><Link className="inv-link" to={`/inventory/lots/${lot.stock_lot_id}`}>{lot.lot_code}</Link><small>{item.ingredient_name}</small></td><td>{dateTime(lot.created_at)}</td><td>{date(lot.expiry_date)}<small>{days === null ? '' : days < 0 ? `Quá hạn ${-days} ngày` : `Còn ${days} ngày`}</small><Badge status={expiryStatus(lot.expiry_date)} /></td><td className="numeric">{quantity(lot.received_quantity)} {item.base_unit.unit_code}</td><td className="numeric">{quantity(lot.current_quantity)} {item.base_unit.unit_code}</td><td className="numeric">{money(multiplyDecimal(lot.current_quantity, lot.unit_cost))}</td><td><Badge status={lot.status} /></td></tr>; })}</tbody></table></div> : <EmptyState title={params.size ? 'Không tìm thấy lô phù hợp' : 'Chưa có lô hàng'} description="Lô được tạo khi chốt phiếu nhập hàng." action={can('viewReceipts') && <Link className="inv-button" to="/inventory/goods-receipts">Mở phiếu nhập</Link>} />}<Pagination page={page} total={query.data.total} pageSize={20} onChange={next => { const values = new URLSearchParams(params); values.set('page',String(next)); setParams(values); }} /></>}</Panel></>;
}
export function MovementTable({rows, labels}: {rows: Movement[]; labels: Record<number, Ingredient>}) {
  const { user } = useInventoryAuth();
  return <div className="inv-table-wrap"><table className="inv-table"><thead><tr><th>Thời gian / mã</th><th>Nguyên liệu / lô</th><th>Nghiệp vụ</th><th>Số lượng</th><th>Nguồn</th><th>Lý do / người thực hiện</th></tr></thead><tbody>{rows.map(row => <tr key={row.stock_movement_id}><td>{dateTime(row.occurred_at)}<small className="inv-code">{row.movement_number}</small></td><td>{labels[row.ingredient_id]?.ingredient_name ?? `Nguyên liệu #${row.ingredient_id}`}<small>{row.stock_lot_id && <Link to={`/inventory/lots/${row.stock_lot_id}`}>Lô #{row.stock_lot_id}</Link>}</small></td><td>{movementLabel(row)}<small><Badge status={row.direction} /></small></td><td className="numeric">{row.direction === 'IN' ? '+' : '−'}{quantity(row.quantity)} {labels[row.ingredient_id]?.base_unit.unit_code ?? 'đơn vị cơ sở'}</td><td>{row.goods_receipt_item_id ? `Dòng phiếu nhập #${row.goods_receipt_item_id}` : row.stocktake_item_id ? `Dòng kiểm kê #${row.stocktake_item_id}` : row.order_item_id ? `Dòng món #${row.order_item_id}` : 'Thao tác thủ công'}</td><td>{row.reason ?? '—'}<small>{row.performed_by === user?.userId ? user.displayName : row.performed_by ? `Nhân viên #${row.performed_by}` : '—'}</small></td></tr>)}</tbody></table></div>;
}
export function MovementsPage() {
  const [params, setParams] = useSearchParams(); const page = Math.max(1,Number(params.get('page')) || 1);
  const query = useQuery(`movements:${params}`, async signal => { if (params.get('from') && params.get('to') && params.get('from')! > params.get('to')!) throw new Error('Ngày kết thúc phải từ ngày bắt đầu trở đi.'); const rows = await get<Page<Movement>>('/inventory/stock-movements', { ingredient_id: params.get('ingredient_id') || undefined, stock_lot_id: params.get('stock_lot_id') || undefined, movement_type: params.get('movement_type') || undefined, occurred_from: params.get('from') ? `${params.get('from')}T00:00:00+07:00` : undefined, occurred_to: params.get('to') ? `${params.get('to')}T23:59:59.999999+07:00` : undefined, limit: 20, offset: (page - 1) * 20 }, signal); return {...rows,labels: await stockLabels(rows.items.map(row => row.ingredient_id),signal)}; });
  return <><PageHeader title="Biến động kho" description="Sổ giao dịch nhập, xuất và điều chỉnh. Thời gian theo múi giờ Việt Nam." actions={<button className="inv-button secondary" onClick={() => window.print()}>In trang đang xem</button>} /><Panel><ListFilters kind="movements" params={params} setParams={setParams} />{query.loading && <LoadingState />}{query.error && <ErrorPanel error={query.error} onRetry={query.refresh} />}{query.data && !query.loading && !query.error && <>{query.data.items.length ? <MovementTable rows={query.data.items} labels={query.data.labels} /> : <EmptyState title="Chưa có biến động phù hợp" description="Thử xóa bộ lọc hoặc chốt một chứng từ nhập, xuất hay kiểm kê." />}<Pagination page={page} total={query.data.total} pageSize={20} onChange={next => { const values = new URLSearchParams(params); values.set('page',String(next)); setParams(values); }} /></>}</Panel></>;
}
export function LotDetailPage() {
  const { can } = useInventoryAuth();
  const {id} = useParams(); const [page,setPage] = useState(1);
  const query = useQuery(`lot:${id}:${page}`, async signal => { const lot = await get<Lot>(`/inventory/stock-lots/${id}`,undefined,signal); const [labels,movements] = await Promise.all([stockLabels([lot.ingredient_id],signal),get<Page<Movement>>('/inventory/stock-movements',{stock_lot_id:lot.stock_lot_id,limit:20,offset:(page-1)*20},signal)]); return {lot,labels,movements}; });
  if (query.loading) return <LoadingState />; if (query.error) return <ErrorPanel error={query.error} onRetry={query.refresh} />; if (!query.data) return null;
  const {lot,labels,movements} = query.data; const item = labels[lot.ingredient_id]; const unit = item.base_unit.unit_code;
  return <><PageHeader title={lot.lot_code} description={`${item.ingredient_name} · ${item.ingredient_code}`} actions={<><Link className="inv-button secondary" to="/inventory/lots">Danh sách lô</Link>{can('adjustStock') && <Link className="inv-button" to={`/inventory/adjustments/new?lot_id=${lot.stock_lot_id}`}>Điều chỉnh lô</Link>}</>} /><Panel title="Thông tin lô"><dl className="inv-detail-grid"><div><dt>Trạng thái</dt><dd><Badge status={lot.status} /></dd></div><div><dt>Hạn dùng</dt><dd>{date(lot.expiry_date)} <Badge status={expiryStatus(lot.expiry_date)} /></dd></div><div><dt>Ngày sản xuất</dt><dd>{date(lot.manufacture_date)}</dd></div><div><dt>Ngày tạo lô</dt><dd>{dateTime(lot.created_at)}</dd></div><div><dt>Dòng nhập nguồn</dt><dd>{lot.goods_receipt_item_id ? `#${lot.goods_receipt_item_id}` : '—'}</dd></div><div><dt>Giá mỗi {unit}</dt><dd>{money(lot.unit_cost)}</dd></div><div><dt>Nhập ban đầu</dt><dd>{quantity(lot.received_quantity)} {unit}</dd></div><div><dt>Còn lại</dt><dd>{quantity(lot.current_quantity)} {unit}</dd></div><div><dt>Chênh lệch giảm ròng từ lúc nhận</dt><dd>{quantity(subtractDecimal(lot.received_quantity,lot.current_quantity))} {unit}</dd></div></dl><p className="inv-note">Giá trị còn lại = lượng còn lại × đơn giá cơ sở của lô: <strong>{money(multiplyDecimal(lot.current_quantity,lot.unit_cost))}</strong>. Chênh lệch giảm ròng bao gồm xuất và các lần điều chỉnh.</p><Link to={`/inventory/ingredients/${item.ingredient_id}`}>Xem nguyên liệu</Link></Panel><Panel title="Lịch sử của lô">{movements.items.length ? <MovementTable rows={movements.items} labels={labels} /> : <EmptyState title="Chưa có biến động" />}<Pagination page={page} pageSize={20} total={movements.total} onChange={setPage} /></Panel></>;
}
