

BEGIN;

SET TIME ZONE 'Asia/Ho_Chi_Minh';

CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE SCHEMA IF NOT EXISTS restaurant_ai;
SET search_path TO restaurant_ai, public;

-- =============================================================================
-- 1. TÀI KHOẢN, PHÂN QUYỀN VÀ NHẬT KÝ
-- =============================================================================

CREATE TABLE IF NOT EXISTS users (
    user_id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username        varchar(50)  NOT NULL,
    password_hash   varchar(255) NOT NULL,
    full_name       varchar(120) NOT NULL,
    email           varchar(150),
    phone           varchar(20),
    status          varchar(20)  NOT NULL DEFAULT 'ACTIVE',
    last_login_at   timestamptz,
    created_at      timestamptz  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      timestamptz  NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_users_username UNIQUE (username),
    CONSTRAINT uq_users_email UNIQUE (email),
    CONSTRAINT ck_users_status CHECK (status IN ('ACTIVE', 'INACTIVE', 'LOCKED'))
);

CREATE TABLE IF NOT EXISTS roles (
    role_id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_code       varchar(50)  NOT NULL,
    role_name       varchar(100) NOT NULL,
    description     text,
    is_active       boolean      NOT NULL DEFAULT true,

    CONSTRAINT uq_roles_role_code UNIQUE (role_code)
);

CREATE TABLE IF NOT EXISTS permissions (
    permission_id   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    permission_code varchar(80)  NOT NULL,
    permission_name varchar(120) NOT NULL,
    description     text,

    CONSTRAINT uq_permissions_permission_code UNIQUE (permission_code)
);

CREATE TABLE IF NOT EXISTS user_roles (
    user_id         bigint      NOT NULL,
    role_id         bigint      NOT NULL,
    assigned_by     bigint,
    assigned_at     timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_user_roles PRIMARY KEY (user_id, role_id),
    CONSTRAINT fk_user_roles_user FOREIGN KEY (user_id)
        REFERENCES users (user_id) ON DELETE CASCADE,
    CONSTRAINT fk_user_roles_role FOREIGN KEY (role_id)
        REFERENCES roles (role_id) ON DELETE CASCADE,
    CONSTRAINT fk_user_roles_assigned_by FOREIGN KEY (assigned_by)
        REFERENCES users (user_id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS role_permissions (
    role_id         bigint NOT NULL,
    permission_id   bigint NOT NULL,

    CONSTRAINT pk_role_permissions PRIMARY KEY (role_id, permission_id),
    CONSTRAINT fk_role_permissions_role FOREIGN KEY (role_id)
        REFERENCES roles (role_id) ON DELETE CASCADE,
    CONSTRAINT fk_role_permissions_permission FOREIGN KEY (permission_id)
        REFERENCES permissions (permission_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS audit_logs (
    audit_log_id    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_user_id   bigint,
    action_code     varchar(80) NOT NULL,
    entity_type     varchar(80) NOT NULL,
    entity_id       varchar(80),
    description     text,
    old_values      jsonb,
    new_values      jsonb,
    ip_address      inet,
    occurred_at     timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_audit_logs_actor FOREIGN KEY (actor_user_id)
        REFERENCES users (user_id) ON DELETE SET NULL,
    CONSTRAINT ck_audit_logs_old_values_object
        CHECK (old_values IS NULL OR jsonb_typeof(old_values) = 'object'),
    CONSTRAINT ck_audit_logs_new_values_object
        CHECK (new_values IS NULL OR jsonb_typeof(new_values) = 'object')
);

-- =============================================================================
-- 2. ĐƠN VỊ, NGUYÊN LIỆU, BÀN, MÓN ĂN VÀ CÔNG THỨC
-- =============================================================================

CREATE TABLE IF NOT EXISTS units (
    unit_id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    unit_code       varchar(20) NOT NULL,
    unit_name       varchar(80) NOT NULL,
    dimension       varchar(20) NOT NULL,
    is_active       boolean     NOT NULL DEFAULT true,

    CONSTRAINT uq_units_unit_code UNIQUE (unit_code),
    CONSTRAINT ck_units_dimension
        CHECK (dimension IN ('MASS', 'VOLUME', 'COUNT', 'LENGTH', 'OTHER'))
);

CREATE TABLE IF NOT EXISTS unit_conversions (
    conversion_id   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    from_unit_id    bigint        NOT NULL,
    to_unit_id      bigint        NOT NULL,
    factor          numeric(18,6) NOT NULL,

    CONSTRAINT uq_unit_conversions_pair UNIQUE (from_unit_id, to_unit_id),
    CONSTRAINT fk_unit_conversions_from FOREIGN KEY (from_unit_id)
        REFERENCES units (unit_id) ON DELETE RESTRICT,
    CONSTRAINT fk_unit_conversions_to FOREIGN KEY (to_unit_id)
        REFERENCES units (unit_id) ON DELETE RESTRICT,
    CONSTRAINT ck_unit_conversions_different_units CHECK (from_unit_id <> to_unit_id),
    CONSTRAINT ck_unit_conversions_factor_positive CHECK (factor > 0)
);

CREATE TABLE IF NOT EXISTS ingredients (
    ingredient_id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ingredient_code         varchar(40)   NOT NULL,
    ingredient_name         varchar(150)  NOT NULL,
    base_unit_id            bigint        NOT NULL,
    manages_lot             boolean       NOT NULL DEFAULT true,
    default_shelf_life_days integer,
    minimum_stock_qty       numeric(14,3) NOT NULL DEFAULT 0,
    safety_stock_qty        numeric(14,3) NOT NULL DEFAULT 0,
    status                  varchar(20)   NOT NULL DEFAULT 'ACTIVE',
    created_at              timestamptz   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at              timestamptz   NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_ingredients_code UNIQUE (ingredient_code),
    CONSTRAINT fk_ingredients_base_unit FOREIGN KEY (base_unit_id)
        REFERENCES units (unit_id) ON DELETE RESTRICT,
    CONSTRAINT ck_ingredients_shelf_life
        CHECK (default_shelf_life_days IS NULL OR default_shelf_life_days >= 0),
    CONSTRAINT ck_ingredients_minimum_stock CHECK (minimum_stock_qty >= 0),
    CONSTRAINT ck_ingredients_safety_stock CHECK (safety_stock_qty >= 0),
    CONSTRAINT ck_ingredients_status CHECK (status IN ('ACTIVE', 'INACTIVE'))
);

CREATE TABLE IF NOT EXISTS dining_tables (
    table_id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    table_code       varchar(30) NOT NULL,
    table_name       varchar(80),
    capacity         integer     NOT NULL,
    status           varchar(20) NOT NULL DEFAULT 'AVAILABLE',
    created_at       timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_dining_tables_code UNIQUE (table_code),
    CONSTRAINT ck_dining_tables_capacity CHECK (capacity > 0),
    CONSTRAINT ck_dining_tables_status
        CHECK (status IN ('AVAILABLE', 'OCCUPIED', 'RESERVED', 'INACTIVE'))
);

CREATE TABLE IF NOT EXISTS menu_categories (
    category_id      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_code    varchar(40)  NOT NULL,
    category_name    varchar(120) NOT NULL,
    description      text,
    display_order    integer      NOT NULL DEFAULT 0,
    status           varchar(20)  NOT NULL DEFAULT 'ACTIVE',

    CONSTRAINT uq_menu_categories_code UNIQUE (category_code),
    CONSTRAINT ck_menu_categories_display_order CHECK (display_order >= 0),
    CONSTRAINT ck_menu_categories_status CHECK (status IN ('ACTIVE', 'INACTIVE'))
);

CREATE TABLE IF NOT EXISTS dishes (
    dish_id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dish_code        varchar(40)   NOT NULL,
    dish_name        varchar(150)  NOT NULL,
    category_id      bigint        NOT NULL,
    selling_price    numeric(14,2) NOT NULL,
    description      text,
    status           varchar(20)   NOT NULL DEFAULT 'ACTIVE',
    created_at       timestamptz   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at       timestamptz   NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_dishes_code UNIQUE (dish_code),
    CONSTRAINT fk_dishes_category FOREIGN KEY (category_id)
        REFERENCES menu_categories (category_id) ON DELETE RESTRICT,
    CONSTRAINT ck_dishes_selling_price CHECK (selling_price >= 0),
    CONSTRAINT ck_dishes_status CHECK (status IN ('ACTIVE', 'INACTIVE', 'SOLD_OUT'))
);

CREATE TABLE IF NOT EXISTS recipe_versions (
    recipe_version_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dish_id            bigint       NOT NULL,
    version_no         integer      NOT NULL,
    status             varchar(20)  NOT NULL DEFAULT 'DRAFT',
    effective_from     date,
    effective_to       date,
    notes              text,
    created_by         bigint,
    created_at         timestamptz  NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_recipe_versions_dish_version UNIQUE (dish_id, version_no),
    CONSTRAINT fk_recipe_versions_dish FOREIGN KEY (dish_id)
        REFERENCES dishes (dish_id) ON DELETE RESTRICT,
    CONSTRAINT fk_recipe_versions_created_by FOREIGN KEY (created_by)
        REFERENCES users (user_id) ON DELETE SET NULL,
    CONSTRAINT ck_recipe_versions_version_no CHECK (version_no > 0),
    CONSTRAINT ck_recipe_versions_dates
        CHECK (effective_to IS NULL OR effective_from IS NULL OR effective_to >= effective_from),
    CONSTRAINT ck_recipe_versions_status
        CHECK (status IN ('DRAFT', 'ACTIVE', 'INACTIVE', 'EXPIRED'))
);

CREATE TABLE IF NOT EXISTS recipe_items (
    recipe_item_id    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipe_version_id bigint        NOT NULL,
    ingredient_id     bigint        NOT NULL,
    quantity          numeric(14,3) NOT NULL,
    unit_id           bigint        NOT NULL,
    base_quantity     numeric(14,3) NOT NULL,

    CONSTRAINT uq_recipe_items_recipe_ingredient
        UNIQUE (recipe_version_id, ingredient_id),
    CONSTRAINT fk_recipe_items_recipe_version FOREIGN KEY (recipe_version_id)
        REFERENCES recipe_versions (recipe_version_id) ON DELETE CASCADE,
    CONSTRAINT fk_recipe_items_ingredient FOREIGN KEY (ingredient_id)
        REFERENCES ingredients (ingredient_id) ON DELETE RESTRICT,
    CONSTRAINT fk_recipe_items_unit FOREIGN KEY (unit_id)
        REFERENCES units (unit_id) ON DELETE RESTRICT,
    CONSTRAINT ck_recipe_items_quantity CHECK (quantity > 0),
    CONSTRAINT ck_recipe_items_base_quantity CHECK (base_quantity > 0)
);

-- =============================================================================
-- 3. ORDER, BẾP VÀ THANH TOÁN
-- =============================================================================

CREATE TABLE IF NOT EXISTS orders (
    order_id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_number        varchar(40)   NOT NULL,
    table_id            bigint        NOT NULL,
    opened_by           bigint        NOT NULL,
    status              varchar(20)   NOT NULL DEFAULT 'OPEN',
    opened_at           timestamptz   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    sent_at             timestamptz,
    completed_at        timestamptz,
    subtotal_amount     numeric(14,2) NOT NULL DEFAULT 0,
    notes               text,
    cancelled_by        bigint,
    cancelled_at        timestamptz,
    cancellation_reason text,

    CONSTRAINT uq_orders_order_number UNIQUE (order_number),
    CONSTRAINT fk_orders_table FOREIGN KEY (table_id)
        REFERENCES dining_tables (table_id) ON DELETE RESTRICT,
    CONSTRAINT fk_orders_opened_by FOREIGN KEY (opened_by)
        REFERENCES users (user_id) ON DELETE RESTRICT,
    CONSTRAINT fk_orders_cancelled_by FOREIGN KEY (cancelled_by)
        REFERENCES users (user_id) ON DELETE SET NULL,
    CONSTRAINT ck_orders_subtotal CHECK (subtotal_amount >= 0),
    CONSTRAINT ck_orders_status
        CHECK (status IN ('OPEN', 'SENT', 'IN_PROGRESS', 'COMPLETED', 'PAID', 'CANCELLED')),
    CONSTRAINT ck_orders_sent_at CHECK (sent_at IS NULL OR sent_at >= opened_at),
    CONSTRAINT ck_orders_completed_at
        CHECK (completed_at IS NULL OR completed_at >= opened_at),
    CONSTRAINT ck_orders_cancellation
        CHECK (
            (status <> 'CANCELLED')
            OR (cancelled_at IS NOT NULL AND cancellation_reason IS NOT NULL)
        )
);

CREATE TABLE IF NOT EXISTS order_items (
    order_item_id       bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id            bigint        NOT NULL,
    dish_id             bigint        NOT NULL,
    recipe_version_id   bigint,
    quantity            integer       NOT NULL,
    unit_price          numeric(14,2) NOT NULL,
    line_amount         numeric(14,2) GENERATED ALWAYS AS (quantity * unit_price) STORED,
    status              varchar(20)   NOT NULL DEFAULT 'PENDING',
    notes               text,
    sent_at             timestamptz,
    completed_at        timestamptz,
    cancelled_by        bigint,
    cancelled_at        timestamptz,
    cancellation_reason text,

    CONSTRAINT fk_order_items_order FOREIGN KEY (order_id)
        REFERENCES orders (order_id) ON DELETE CASCADE,
    CONSTRAINT fk_order_items_dish FOREIGN KEY (dish_id)
        REFERENCES dishes (dish_id) ON DELETE RESTRICT,
    CONSTRAINT fk_order_items_recipe_version FOREIGN KEY (recipe_version_id)
        REFERENCES recipe_versions (recipe_version_id) ON DELETE RESTRICT,
    CONSTRAINT fk_order_items_cancelled_by FOREIGN KEY (cancelled_by)
        REFERENCES users (user_id) ON DELETE SET NULL,
    CONSTRAINT ck_order_items_quantity CHECK (quantity > 0),
    CONSTRAINT ck_order_items_unit_price CHECK (unit_price >= 0),
    CONSTRAINT ck_order_items_status
        CHECK (status IN ('PENDING', 'SENT', 'PREPARING', 'COMPLETED', 'CANCELLED')),
    CONSTRAINT ck_order_items_cancellation
        CHECK (
            (status <> 'CANCELLED')
            OR (cancelled_at IS NOT NULL AND cancellation_reason IS NOT NULL)
        )
);

CREATE TABLE IF NOT EXISTS payments (
    payment_id      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_number  varchar(40)   NOT NULL,
    order_id        bigint        NOT NULL,
    amount          numeric(14,2) NOT NULL,
    payment_method  varchar(20)   NOT NULL,
    received_by     bigint        NOT NULL,
    paid_at         timestamptz   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    notes           text,

    CONSTRAINT uq_payments_number UNIQUE (payment_number),
    CONSTRAINT uq_payments_order UNIQUE (order_id),
    CONSTRAINT fk_payments_order FOREIGN KEY (order_id)
        REFERENCES orders (order_id) ON DELETE RESTRICT,
    CONSTRAINT fk_payments_received_by FOREIGN KEY (received_by)
        REFERENCES users (user_id) ON DELETE RESTRICT,
    CONSTRAINT ck_payments_amount CHECK (amount > 0),
    CONSTRAINT ck_payments_method
        CHECK (payment_method IN ('CASH', 'CARD', 'BANK_TRANSFER', 'E_WALLET'))
);

-- =============================================================================
-- 4. NHÀ CUNG CẤP
-- =============================================================================

CREATE TABLE IF NOT EXISTS suppliers (
    supplier_id     bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_code   varchar(40)  NOT NULL,
    supplier_name   varchar(180) NOT NULL,
    contact_name    varchar(120),
    phone           varchar(20),
    email           varchar(150),
    address         text,
    tax_code        varchar(30),
    status          varchar(20)  NOT NULL DEFAULT 'ACTIVE',
    created_at      timestamptz  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      timestamptz  NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_suppliers_code UNIQUE (supplier_code),
    CONSTRAINT ck_suppliers_status CHECK (status IN ('ACTIVE', 'INACTIVE', 'SUSPENDED'))
);

CREATE TABLE IF NOT EXISTS supplier_ingredients (
    supplier_ingredient_id       bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_id                  bigint        NOT NULL,
    ingredient_id                bigint        NOT NULL,
    supplier_sku                 varchar(80),
    purchase_unit_id             bigint        NOT NULL,
    base_qty_per_purchase_unit   numeric(14,3) NOT NULL,
    lead_time_days               integer       NOT NULL DEFAULT 0,
    minimum_order_qty            numeric(14,3) NOT NULL DEFAULT 1,
    latest_unit_price            numeric(14,2),
    is_preferred                 boolean       NOT NULL DEFAULT false,
    is_active                    boolean       NOT NULL DEFAULT true,

    CONSTRAINT uq_supplier_ingredients_supplier_ingredient
        UNIQUE (supplier_id, ingredient_id),
    CONSTRAINT fk_supplier_ingredients_supplier FOREIGN KEY (supplier_id)
        REFERENCES suppliers (supplier_id) ON DELETE RESTRICT,
    CONSTRAINT fk_supplier_ingredients_ingredient FOREIGN KEY (ingredient_id)
        REFERENCES ingredients (ingredient_id) ON DELETE RESTRICT,
    CONSTRAINT fk_supplier_ingredients_purchase_unit FOREIGN KEY (purchase_unit_id)
        REFERENCES units (unit_id) ON DELETE RESTRICT,
    CONSTRAINT ck_supplier_ingredients_base_qty CHECK (base_qty_per_purchase_unit > 0),
    CONSTRAINT ck_supplier_ingredients_lead_time CHECK (lead_time_days >= 0),
    CONSTRAINT ck_supplier_ingredients_minimum_order CHECK (minimum_order_qty > 0),
    CONSTRAINT ck_supplier_ingredients_price
        CHECK (latest_unit_price IS NULL OR latest_unit_price >= 0)
);

-- =============================================================================
-- 5. AI/ML, DỰ BÁO VÀ ĐỀ XUẤT NHẬP HÀNG
-- =============================================================================

CREATE TABLE IF NOT EXISTS model_versions (
    model_version_id   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    model_name         varchar(120) NOT NULL,
    algorithm          varchar(100) NOT NULL,
    version_label      varchar(40)  NOT NULL,
    parameters         jsonb        NOT NULL DEFAULT '{}'::jsonb,
    feature_config     jsonb        NOT NULL DEFAULT '{}'::jsonb,
    trained_at         timestamptz,
    training_data_from date,
    training_data_to   date,
    status             varchar(20)  NOT NULL DEFAULT 'INACTIVE',
    created_by         bigint,
    notes              text,
    created_at         timestamptz  NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_model_versions_name_version UNIQUE (model_name, version_label),
    CONSTRAINT fk_model_versions_created_by FOREIGN KEY (created_by)
        REFERENCES users (user_id) ON DELETE SET NULL,
    CONSTRAINT ck_model_versions_parameters_object
        CHECK (jsonb_typeof(parameters) = 'object'),
    CONSTRAINT ck_model_versions_feature_config_object
        CHECK (jsonb_typeof(feature_config) = 'object'),
    CONSTRAINT ck_model_versions_training_dates
        CHECK (training_data_to IS NULL OR training_data_from IS NULL
               OR training_data_to >= training_data_from),
    CONSTRAINT ck_model_versions_status
        CHECK (status IN ('TRAINING', 'ACTIVE', 'INACTIVE', 'FAILED', 'ARCHIVED'))
);

CREATE TABLE IF NOT EXISTS model_metrics (
    metric_id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    model_version_id  bigint        NOT NULL,
    metric_name       varchar(40)   NOT NULL,
    metric_value      numeric(18,6) NOT NULL,
    dataset_scope     varchar(20)   NOT NULL,
    calculated_at     timestamptz   NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_model_metrics_version_name_scope
        UNIQUE (model_version_id, metric_name, dataset_scope),
    CONSTRAINT fk_model_metrics_version FOREIGN KEY (model_version_id)
        REFERENCES model_versions (model_version_id) ON DELETE CASCADE,
    CONSTRAINT ck_model_metrics_scope
        CHECK (dataset_scope IN ('TRAIN', 'VALIDATION', 'TEST', 'PRODUCTION'))
);

CREATE TABLE IF NOT EXISTS forecast_runs (
    forecast_run_id      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    model_version_id     bigint      NOT NULL,
    forecast_start_date  date        NOT NULL,
    forecast_end_date    date        NOT NULL,
    horizon_days         integer     NOT NULL,
    trigger_type         varchar(20) NOT NULL,
    status               varchar(20) NOT NULL DEFAULT 'PENDING',
    generated_by         bigint,
    generated_at         timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    error_message        text,

    CONSTRAINT fk_forecast_runs_model_version FOREIGN KEY (model_version_id)
        REFERENCES model_versions (model_version_id) ON DELETE RESTRICT,
    CONSTRAINT fk_forecast_runs_generated_by FOREIGN KEY (generated_by)
        REFERENCES users (user_id) ON DELETE SET NULL,
    CONSTRAINT ck_forecast_runs_dates CHECK (forecast_end_date >= forecast_start_date),
    CONSTRAINT ck_forecast_runs_horizon CHECK (horizon_days > 0),
    CONSTRAINT ck_forecast_runs_trigger
        CHECK (trigger_type IN ('MANUAL', 'SCHEDULED')),
    CONSTRAINT ck_forecast_runs_status
        CHECK (status IN ('PENDING', 'RUNNING', 'COMPLETED', 'FAILED')),
    CONSTRAINT ck_forecast_runs_error
        CHECK (status <> 'FAILED' OR error_message IS NOT NULL)
);

CREATE TABLE IF NOT EXISTS forecast_results (
    forecast_result_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    forecast_run_id    bigint        NOT NULL,
    dish_id            bigint        NOT NULL,
    forecast_date      date          NOT NULL,
    predicted_qty      numeric(14,3) NOT NULL,
    lower_bound        numeric(14,3),
    upper_bound        numeric(14,3),
    actual_qty         numeric(14,3),

    CONSTRAINT uq_forecast_results_run_dish_date
        UNIQUE (forecast_run_id, dish_id, forecast_date),
    CONSTRAINT fk_forecast_results_run FOREIGN KEY (forecast_run_id)
        REFERENCES forecast_runs (forecast_run_id) ON DELETE CASCADE,
    CONSTRAINT fk_forecast_results_dish FOREIGN KEY (dish_id)
        REFERENCES dishes (dish_id) ON DELETE RESTRICT,
    CONSTRAINT ck_forecast_results_predicted CHECK (predicted_qty >= 0),
    CONSTRAINT ck_forecast_results_lower CHECK (lower_bound IS NULL OR lower_bound >= 0),
    CONSTRAINT ck_forecast_results_upper
        CHECK (upper_bound IS NULL OR upper_bound >= predicted_qty),
    CONSTRAINT ck_forecast_results_bounds
        CHECK (lower_bound IS NULL OR lower_bound <= predicted_qty),
    CONSTRAINT ck_forecast_results_actual CHECK (actual_qty IS NULL OR actual_qty >= 0)
);

CREATE TABLE IF NOT EXISTS replenishment_proposals (
    proposal_id        bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    proposal_number    varchar(40) NOT NULL,
    forecast_run_id    bigint      NOT NULL,
    planning_start_date date       NOT NULL,
    planning_end_date  date        NOT NULL,
    status             varchar(20) NOT NULL DEFAULT 'DRAFT',
    created_at         timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    reviewed_by        bigint,
    reviewed_at        timestamptz,
    decision_reason    text,

    CONSTRAINT uq_replenishment_proposals_number UNIQUE (proposal_number),
    CONSTRAINT fk_replenishment_proposals_run FOREIGN KEY (forecast_run_id)
        REFERENCES forecast_runs (forecast_run_id) ON DELETE RESTRICT,
    CONSTRAINT fk_replenishment_proposals_reviewed_by FOREIGN KEY (reviewed_by)
        REFERENCES users (user_id) ON DELETE SET NULL,
    CONSTRAINT ck_replenishment_proposals_dates
        CHECK (planning_end_date >= planning_start_date),
    CONSTRAINT ck_replenishment_proposals_status
        CHECK (status IN ('DRAFT', 'PENDING_REVIEW', 'APPROVED', 'REJECTED', 'ORDERED')),
    CONSTRAINT ck_replenishment_proposals_review
        CHECK (
            status NOT IN ('APPROVED', 'REJECTED')
            OR (reviewed_by IS NOT NULL AND reviewed_at IS NOT NULL)
        )
);

CREATE TABLE IF NOT EXISTS replenishment_proposal_items (
    proposal_item_id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    proposal_id               bigint        NOT NULL,
    ingredient_id             bigint        NOT NULL,
    forecast_demand_qty       numeric(14,3) NOT NULL,
    available_stock_qty       numeric(14,3) NOT NULL,
    incoming_qty              numeric(14,3) NOT NULL,
    safety_stock_qty          numeric(14,3) NOT NULL,
    lead_time_days_snapshot   integer       NOT NULL,
    suggested_qty             numeric(14,3) NOT NULL,
    adjusted_qty              numeric(14,3),
    final_qty                 numeric(14,3)
        GENERATED ALWAYS AS (COALESCE(adjusted_qty, suggested_qty)) STORED,
    preferred_supplier_id     bigint,
    adjustment_reason         text,

    CONSTRAINT uq_replenishment_items_proposal_ingredient
        UNIQUE (proposal_id, ingredient_id),
    CONSTRAINT fk_replenishment_items_proposal FOREIGN KEY (proposal_id)
        REFERENCES replenishment_proposals (proposal_id) ON DELETE CASCADE,
    CONSTRAINT fk_replenishment_items_ingredient FOREIGN KEY (ingredient_id)
        REFERENCES ingredients (ingredient_id) ON DELETE RESTRICT,
    CONSTRAINT fk_replenishment_items_supplier FOREIGN KEY (preferred_supplier_id)
        REFERENCES suppliers (supplier_id) ON DELETE SET NULL,
    CONSTRAINT ck_replenishment_items_demand CHECK (forecast_demand_qty >= 0),
    CONSTRAINT ck_replenishment_items_available CHECK (available_stock_qty >= 0),
    CONSTRAINT ck_replenishment_items_incoming CHECK (incoming_qty >= 0),
    CONSTRAINT ck_replenishment_items_safety CHECK (safety_stock_qty >= 0),
    CONSTRAINT ck_replenishment_items_lead_time CHECK (lead_time_days_snapshot >= 0),
    CONSTRAINT ck_replenishment_items_suggested CHECK (suggested_qty >= 0),
    CONSTRAINT ck_replenishment_items_adjusted
        CHECK (adjusted_qty IS NULL OR adjusted_qty >= 0),
    CONSTRAINT ck_replenishment_items_adjustment_reason
        CHECK (adjusted_qty IS NULL OR adjustment_reason IS NOT NULL)
);

-- =============================================================================
-- 6. MUA HÀNG, NHẬP KHO VÀ TỒN KHO
-- =============================================================================

CREATE TABLE IF NOT EXISTS purchase_orders (
    purchase_order_id       bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    purchase_order_number   varchar(40)   NOT NULL,
    supplier_id             bigint        NOT NULL,
    proposal_id             bigint,
    status                  varchar(25)   NOT NULL DEFAULT 'DRAFT',
    order_date              date          NOT NULL DEFAULT CURRENT_DATE,
    expected_delivery_date  date,
    created_by              bigint        NOT NULL,
    approved_by             bigint,
    subtotal_amount         numeric(14,2) NOT NULL DEFAULT 0,
    notes                   text,
    cancelled_at            timestamptz,
    cancellation_reason     text,
    created_at              timestamptz   NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_purchase_orders_number UNIQUE (purchase_order_number),
    CONSTRAINT fk_purchase_orders_supplier FOREIGN KEY (supplier_id)
        REFERENCES suppliers (supplier_id) ON DELETE RESTRICT,
    CONSTRAINT fk_purchase_orders_proposal FOREIGN KEY (proposal_id)
        REFERENCES replenishment_proposals (proposal_id) ON DELETE SET NULL,
    CONSTRAINT fk_purchase_orders_created_by FOREIGN KEY (created_by)
        REFERENCES users (user_id) ON DELETE RESTRICT,
    CONSTRAINT fk_purchase_orders_approved_by FOREIGN KEY (approved_by)
        REFERENCES users (user_id) ON DELETE SET NULL,
    CONSTRAINT ck_purchase_orders_status
        CHECK (status IN ('DRAFT', 'PENDING_APPROVAL', 'APPROVED', 'ORDERED',
                          'PARTIALLY_RECEIVED', 'RECEIVED', 'CANCELLED')),
    CONSTRAINT ck_purchase_orders_delivery_date
        CHECK (expected_delivery_date IS NULL OR expected_delivery_date >= order_date),
    CONSTRAINT ck_purchase_orders_subtotal CHECK (subtotal_amount >= 0),
    CONSTRAINT ck_purchase_orders_cancelled
        CHECK (
            status <> 'CANCELLED'
            OR (cancelled_at IS NOT NULL AND cancellation_reason IS NOT NULL)
        )
);

CREATE TABLE IF NOT EXISTS purchase_order_items (
    purchase_order_item_id       bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    purchase_order_id            bigint        NOT NULL,
    supplier_ingredient_id       bigint        NOT NULL,
    purchase_unit_id             bigint        NOT NULL,
    ordered_quantity             numeric(14,3) NOT NULL,
    base_qty_per_purchase_unit   numeric(14,3) NOT NULL,
    ordered_base_qty             numeric(14,3)
        GENERATED ALWAYS AS (ordered_quantity * base_qty_per_purchase_unit) STORED,
    expected_unit_price          numeric(14,2) NOT NULL,
    line_amount                  numeric(14,2)
        GENERATED ALWAYS AS (ordered_quantity * expected_unit_price) STORED,

    CONSTRAINT uq_purchase_order_items_order_supplier_ingredient
        UNIQUE (purchase_order_id, supplier_ingredient_id),
    CONSTRAINT fk_purchase_order_items_order FOREIGN KEY (purchase_order_id)
        REFERENCES purchase_orders (purchase_order_id) ON DELETE CASCADE,
    CONSTRAINT fk_purchase_order_items_supplier_ingredient
        FOREIGN KEY (supplier_ingredient_id)
        REFERENCES supplier_ingredients (supplier_ingredient_id) ON DELETE RESTRICT,
    CONSTRAINT fk_purchase_order_items_unit FOREIGN KEY (purchase_unit_id)
        REFERENCES units (unit_id) ON DELETE RESTRICT,
    CONSTRAINT ck_purchase_order_items_quantity CHECK (ordered_quantity > 0),
    CONSTRAINT ck_purchase_order_items_base_qty CHECK (base_qty_per_purchase_unit > 0),
    CONSTRAINT ck_purchase_order_items_price CHECK (expected_unit_price >= 0)
);

CREATE TABLE IF NOT EXISTS goods_receipts (
    goods_receipt_id     bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    receipt_number       varchar(40) NOT NULL,
    purchase_order_id    bigint      NOT NULL,
    receipt_date         date        NOT NULL DEFAULT CURRENT_DATE,
    supplier_document_no varchar(80),
    status               varchar(20) NOT NULL DEFAULT 'DRAFT',
    received_by          bigint      NOT NULL,
    notes                text,
    created_at           timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_goods_receipts_number UNIQUE (receipt_number),
    CONSTRAINT fk_goods_receipts_purchase_order FOREIGN KEY (purchase_order_id)
        REFERENCES purchase_orders (purchase_order_id) ON DELETE RESTRICT,
    CONSTRAINT fk_goods_receipts_received_by FOREIGN KEY (received_by)
        REFERENCES users (user_id) ON DELETE RESTRICT,
    CONSTRAINT ck_goods_receipts_status
        CHECK (status IN ('DRAFT', 'CONFIRMED', 'CANCELLED'))
);

CREATE TABLE IF NOT EXISTS goods_receipt_items (
    goods_receipt_item_id  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    goods_receipt_id       bigint        NOT NULL,
    purchase_order_item_id bigint        NOT NULL,
    received_quantity      numeric(14,3) NOT NULL,
    purchase_unit_id       bigint        NOT NULL,
    base_quantity          numeric(14,3) NOT NULL,
    actual_unit_price      numeric(14,2) NOT NULL,
    line_amount            numeric(14,2)
        GENERATED ALWAYS AS (received_quantity * actual_unit_price) STORED,
    lot_code               varchar(80),
    manufacture_date       date,
    expiry_date            date,

    CONSTRAINT fk_goods_receipt_items_receipt FOREIGN KEY (goods_receipt_id)
        REFERENCES goods_receipts (goods_receipt_id) ON DELETE CASCADE,
    CONSTRAINT fk_goods_receipt_items_purchase_order_item
        FOREIGN KEY (purchase_order_item_id)
        REFERENCES purchase_order_items (purchase_order_item_id) ON DELETE RESTRICT,
    CONSTRAINT fk_goods_receipt_items_unit FOREIGN KEY (purchase_unit_id)
        REFERENCES units (unit_id) ON DELETE RESTRICT,
    CONSTRAINT ck_goods_receipt_items_received_qty CHECK (received_quantity > 0),
    CONSTRAINT ck_goods_receipt_items_base_qty CHECK (base_quantity > 0),
    CONSTRAINT ck_goods_receipt_items_price CHECK (actual_unit_price >= 0),
    CONSTRAINT ck_goods_receipt_items_dates
        CHECK (expiry_date IS NULL OR manufacture_date IS NULL OR expiry_date >= manufacture_date)
);

CREATE TABLE IF NOT EXISTS stock_lots (
    stock_lot_id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ingredient_id        bigint        NOT NULL,
    goods_receipt_item_id bigint,
    lot_code             varchar(80)   NOT NULL,
    manufacture_date     date,
    expiry_date          date,
    received_quantity    numeric(14,3) NOT NULL,
    current_quantity     numeric(14,3) NOT NULL,
    unit_cost            numeric(14,4) NOT NULL,
    status               varchar(20)   NOT NULL DEFAULT 'ACTIVE',
    created_at           timestamptz   NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_stock_lots_ingredient_lot UNIQUE (ingredient_id, lot_code),
    CONSTRAINT uq_stock_lots_goods_receipt_item UNIQUE (goods_receipt_item_id),
    CONSTRAINT fk_stock_lots_ingredient FOREIGN KEY (ingredient_id)
        REFERENCES ingredients (ingredient_id) ON DELETE RESTRICT,
    CONSTRAINT fk_stock_lots_goods_receipt_item FOREIGN KEY (goods_receipt_item_id)
        REFERENCES goods_receipt_items (goods_receipt_item_id) ON DELETE RESTRICT,
    CONSTRAINT ck_stock_lots_received_qty CHECK (received_quantity > 0),
    CONSTRAINT ck_stock_lots_current_qty
        CHECK (current_quantity >= 0 AND current_quantity <= received_quantity),
    CONSTRAINT ck_stock_lots_unit_cost CHECK (unit_cost >= 0),
    CONSTRAINT ck_stock_lots_dates
        CHECK (expiry_date IS NULL OR manufacture_date IS NULL OR expiry_date >= manufacture_date),
    CONSTRAINT ck_stock_lots_status
        CHECK (status IN ('ACTIVE', 'DEPLETED', 'EXPIRED', 'BLOCKED'))
);

CREATE TABLE IF NOT EXISTS stocktakes (
    stocktake_id      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stocktake_number  varchar(40) NOT NULL,
    status            varchar(20) NOT NULL DEFAULT 'DRAFT',
    started_at        timestamptz,
    completed_at      timestamptz,
    created_by        bigint      NOT NULL,
    completed_by      bigint,
    notes             text,
    created_at        timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_stocktakes_number UNIQUE (stocktake_number),
    CONSTRAINT fk_stocktakes_created_by FOREIGN KEY (created_by)
        REFERENCES users (user_id) ON DELETE RESTRICT,
    CONSTRAINT fk_stocktakes_completed_by FOREIGN KEY (completed_by)
        REFERENCES users (user_id) ON DELETE SET NULL,
    CONSTRAINT ck_stocktakes_status
        CHECK (status IN ('DRAFT', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED')),
    CONSTRAINT ck_stocktakes_dates
        CHECK (completed_at IS NULL OR started_at IS NULL OR completed_at >= started_at),
    CONSTRAINT ck_stocktakes_completed
        CHECK (status <> 'COMPLETED' OR (completed_at IS NOT NULL AND completed_by IS NOT NULL))
);

CREATE TABLE IF NOT EXISTS stocktake_items (
    stocktake_item_id  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stocktake_id       bigint        NOT NULL,
    stock_lot_id       bigint        NOT NULL,
    system_quantity    numeric(14,3) NOT NULL,
    actual_quantity    numeric(14,3) NOT NULL,
    variance_quantity  numeric(14,3)
        GENERATED ALWAYS AS (actual_quantity - system_quantity) STORED,
    adjustment_reason  text,

    CONSTRAINT uq_stocktake_items_stocktake_lot UNIQUE (stocktake_id, stock_lot_id),
    CONSTRAINT fk_stocktake_items_stocktake FOREIGN KEY (stocktake_id)
        REFERENCES stocktakes (stocktake_id) ON DELETE CASCADE,
    CONSTRAINT fk_stocktake_items_stock_lot FOREIGN KEY (stock_lot_id)
        REFERENCES stock_lots (stock_lot_id) ON DELETE RESTRICT,
    CONSTRAINT ck_stocktake_items_system_qty CHECK (system_quantity >= 0),
    CONSTRAINT ck_stocktake_items_actual_qty CHECK (actual_quantity >= 0),
    CONSTRAINT ck_stocktake_items_adjustment_reason
        CHECK (actual_quantity = system_quantity OR adjustment_reason IS NOT NULL)
);

CREATE TABLE IF NOT EXISTS stock_movements (
    stock_movement_id    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    movement_number      varchar(50)   NOT NULL,
    ingredient_id        bigint        NOT NULL,
    stock_lot_id         bigint,
    movement_type        varchar(25)   NOT NULL,
    direction            varchar(3)    NOT NULL,
    quantity             numeric(14,3) NOT NULL,
    occurred_at          timestamptz   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    performed_by         bigint,
    order_item_id        bigint,
    goods_receipt_item_id bigint,
    stocktake_item_id    bigint,
    reason               text,
    created_at           timestamptz   NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_stock_movements_ingredient FOREIGN KEY (ingredient_id)
        REFERENCES ingredients (ingredient_id) ON DELETE RESTRICT,
    CONSTRAINT fk_stock_movements_stock_lot FOREIGN KEY (stock_lot_id)
        REFERENCES stock_lots (stock_lot_id) ON DELETE RESTRICT,
    CONSTRAINT fk_stock_movements_performed_by FOREIGN KEY (performed_by)
        REFERENCES users (user_id) ON DELETE SET NULL,
    CONSTRAINT fk_stock_movements_order_item FOREIGN KEY (order_item_id)
        REFERENCES order_items (order_item_id) ON DELETE SET NULL,
    CONSTRAINT fk_stock_movements_goods_receipt_item FOREIGN KEY (goods_receipt_item_id)
        REFERENCES goods_receipt_items (goods_receipt_item_id) ON DELETE SET NULL,
    CONSTRAINT fk_stock_movements_stocktake_item FOREIGN KEY (stocktake_item_id)
        REFERENCES stocktake_items (stocktake_item_id) ON DELETE SET NULL,
    CONSTRAINT ck_stock_movements_type
        CHECK (movement_type IN ('RECEIPT', 'CONSUMPTION', 'ADJUSTMENT', 'RETURN')),
    CONSTRAINT ck_stock_movements_direction CHECK (direction IN ('IN', 'OUT')),
    CONSTRAINT ck_stock_movements_quantity CHECK (quantity > 0)
);

-- =============================================================================
-- 7. INDEX PHỤC VỤ TRA CỨU VÀ NGHIỆP VỤ
-- =============================================================================

-- Mỗi bàn chỉ có tối đa một order chưa kết thúc thanh toán/hủy.
CREATE UNIQUE INDEX IF NOT EXISTS uq_orders_one_active_per_table
    ON orders (table_id)
    WHERE status IN ('OPEN', 'SENT', 'IN_PROGRESS', 'COMPLETED');

-- Mỗi món chỉ có tối đa một công thức đang hiệu lực.
CREATE UNIQUE INDEX IF NOT EXISTS uq_recipe_versions_one_active_per_dish
    ON recipe_versions (dish_id)
    WHERE status = 'ACTIVE';

-- Mỗi nguyên liệu chỉ có tối đa một nhà cung cấp ưu tiên đang hoạt động.
CREATE UNIQUE INDEX IF NOT EXISTS uq_supplier_ingredients_one_preferred
    ON supplier_ingredients (ingredient_id)
    WHERE is_preferred = true AND is_active = true;

-- Mỗi tên model chỉ có tối đa một phiên bản ACTIVE.
CREATE UNIQUE INDEX IF NOT EXISTS uq_model_versions_one_active
    ON model_versions (model_name)
    WHERE status = 'ACTIVE';

CREATE INDEX IF NOT EXISTS ix_audit_logs_actor_time
    ON audit_logs (actor_user_id, occurred_at DESC);
CREATE INDEX IF NOT EXISTS ix_audit_logs_entity
    ON audit_logs (entity_type, entity_id);
CREATE INDEX IF NOT EXISTS ix_ingredients_base_unit ON ingredients (base_unit_id);
CREATE INDEX IF NOT EXISTS ix_dishes_category_status ON dishes (category_id, status);
CREATE INDEX IF NOT EXISTS ix_recipe_items_ingredient ON recipe_items (ingredient_id);
CREATE INDEX IF NOT EXISTS ix_orders_status_opened_at ON orders (status, opened_at DESC);
CREATE INDEX IF NOT EXISTS ix_order_items_order_status ON order_items (order_id, status);
CREATE INDEX IF NOT EXISTS ix_order_items_dish ON order_items (dish_id);
CREATE INDEX IF NOT EXISTS ix_payments_paid_at ON payments (paid_at DESC);
CREATE INDEX IF NOT EXISTS ix_supplier_ingredients_ingredient
    ON supplier_ingredients (ingredient_id, is_active);
CREATE INDEX IF NOT EXISTS ix_forecast_runs_model_date
    ON forecast_runs (model_version_id, forecast_start_date, forecast_end_date);
CREATE INDEX IF NOT EXISTS ix_forecast_results_dish_date
    ON forecast_results (dish_id, forecast_date);
CREATE INDEX IF NOT EXISTS ix_replenishment_proposals_status
    ON replenishment_proposals (status, created_at DESC);
CREATE INDEX IF NOT EXISTS ix_replenishment_items_supplier
    ON replenishment_proposal_items (preferred_supplier_id);
CREATE INDEX IF NOT EXISTS ix_purchase_orders_supplier_status
    ON purchase_orders (supplier_id, status, order_date DESC);
CREATE INDEX IF NOT EXISTS ix_purchase_orders_proposal ON purchase_orders (proposal_id);
CREATE INDEX IF NOT EXISTS ix_goods_receipts_order ON goods_receipts (purchase_order_id);
CREATE INDEX IF NOT EXISTS ix_goods_receipt_items_order_item
    ON goods_receipt_items (purchase_order_item_id);
CREATE INDEX IF NOT EXISTS ix_stock_lots_ingredient_expiry
    ON stock_lots (ingredient_id, status, expiry_date);
CREATE INDEX IF NOT EXISTS ix_stock_movements_ingredient_time
    ON stock_movements (ingredient_id, occurred_at DESC);
CREATE INDEX IF NOT EXISTS ix_stock_movements_lot_time
    ON stock_movements (stock_lot_id, occurred_at DESC);
CREATE INDEX IF NOT EXISTS ix_stock_movements_order_item ON stock_movements (order_item_id);
CREATE INDEX IF NOT EXISTS ix_stocktake_items_lot ON stocktake_items (stock_lot_id);

-- =============================================================================
-- 8. MÔ TẢ BẢNG
-- =============================================================================

COMMENT ON SCHEMA restaurant_ai IS
    'CSDL quản lý nhà hàng tích hợp dự báo nhu cầu nguyên liệu và đề xuất nhập hàng';
COMMENT ON TABLE users IS 'Tài khoản người dùng nội bộ';
COMMENT ON TABLE roles IS 'Vai trò nghiệp vụ trong hệ thống';
COMMENT ON TABLE permissions IS 'Danh mục quyền truy cập';
COMMENT ON TABLE audit_logs IS 'Nhật ký các thao tác quan trọng';
COMMENT ON TABLE units IS 'Danh mục đơn vị tính';
COMMENT ON TABLE unit_conversions IS
    'Quy đổi đơn vị: số lượng ở from_unit nhân factor bằng số lượng ở to_unit';
COMMENT ON TABLE ingredients IS 'Danh mục nguyên liệu và ngưỡng tồn kho';
COMMENT ON TABLE recipe_versions IS 'Lịch sử phiên bản công thức của món';
COMMENT ON TABLE orders IS 'Order phục vụ tại bàn';
COMMENT ON TABLE order_items IS 'Các món trong order và trạng thái xử lý tại bếp';
COMMENT ON TABLE payments IS 'Thanh toán; mỗi order chỉ thanh toán một lần';
COMMENT ON TABLE supplier_ingredients IS 'Nguyên liệu do từng nhà cung cấp cung ứng';
COMMENT ON TABLE forecast_results IS 'Số lượng món dự báo theo ngày';
COMMENT ON TABLE replenishment_proposals IS 'Đề xuất nhập hàng chờ quản lý duyệt';
COMMENT ON TABLE stock_lots IS 'Tồn kho theo lô nguyên liệu';
COMMENT ON TABLE stock_movements IS 'Sổ phát sinh nhập, xuất và điều chỉnh kho';

COMMIT;

-- =============================================================================
-- 9. DỮ LIỆU MẪU
-- Chạy phần này sau khi phần cấu trúc phía trên đã COMMIT thành công.
-- Các câu lệnh dùng ON CONFLICT để có thể chạy lại an toàn.
-- =============================================================================

BEGIN;
SET search_path TO restaurant_ai, public;

INSERT INTO roles (role_code, role_name, description) VALUES
    ('ADMIN',        'Quản trị viên',       'Quản trị tài khoản, vai trò và cấu hình'),
    ('MANAGER',      'Quản lý nhà hàng',    'Duyệt mua hàng, theo dõi vận hành và báo cáo'),
    ('WAITER',       'Nhân viên phục vụ',   'Mở bàn, tạo order và gửi món'),
    ('KITCHEN',      'Nhân viên bếp',       'Tiếp nhận và hoàn thành món'),
    ('CASHIER',      'Thu ngân',            'Thanh toán order'),
    ('WAREHOUSE',    'Nhân viên kho',       'Nhập kho, kiểm kê và quản lý tồn'),
    ('DATA_ANALYST', 'Nhân viên phân tích', 'Quản lý model và chạy dự báo')
ON CONFLICT (role_code) DO NOTHING;

INSERT INTO permissions (permission_code, permission_name) VALUES
    ('USER_MANAGE',       'Quản lý tài khoản'),
    ('ROLE_MANAGE',       'Quản lý vai trò và quyền'),
    ('MENU_MANAGE',       'Quản lý món và danh mục'),
    ('RECIPE_MANAGE',     'Quản lý công thức'),
    ('TABLE_MANAGE',      'Quản lý bàn'),
    ('ORDER_CREATE',      'Tạo và cập nhật order'),
    ('KITCHEN_PROCESS',   'Xử lý món tại bếp'),
    ('PAYMENT_CREATE',    'Ghi nhận thanh toán'),
    ('INVENTORY_MANAGE',  'Quản lý kho'),
    ('PURCHASE_MANAGE',   'Lập đơn mua hàng'),
    ('PURCHASE_APPROVE',  'Duyệt đơn mua hàng'),
    ('FORECAST_RUN',      'Chạy dự báo'),
    ('PROPOSAL_REVIEW',   'Duyệt đề xuất nhập hàng'),
    ('REPORT_VIEW',       'Xem báo cáo')
ON CONFLICT (permission_code) DO NOTHING;

INSERT INTO users (username, password_hash, full_name, email, phone) VALUES
    ('admin',     crypt('Admin@123', gen_salt('bf', 10)), 'Quản trị hệ thống', 'admin@restaurant.local',     '0900000001'),
    ('manager',   crypt('Demo@123',  gen_salt('bf', 10)), 'Nguyễn Minh Quản',  'manager@restaurant.local',   '0900000002'),
    ('waiter01',  crypt('Demo@123',  gen_salt('bf', 10)), 'Trần Anh Phục',     'waiter01@restaurant.local',  '0900000003'),
    ('kitchen01', crypt('Demo@123',  gen_salt('bf', 10)), 'Lê Ngọc Bếp',       'kitchen01@restaurant.local', '0900000004'),
    ('cashier01', crypt('Demo@123',  gen_salt('bf', 10)), 'Phạm Thu Ngân',     'cashier01@restaurant.local', '0900000005'),
    ('warehouse', crypt('Demo@123',  gen_salt('bf', 10)), 'Võ Minh Kho',       'warehouse@restaurant.local', '0900000006'),
    ('analyst01', crypt('Demo@123',  gen_salt('bf', 10)), 'Đặng An Phân Tích', 'analyst01@restaurant.local', '0900000007')
ON CONFLICT (username) DO NOTHING;

INSERT INTO user_roles (user_id, role_id, assigned_by)
SELECT u.user_id, r.role_id, a.user_id
FROM (VALUES
    ('admin', 'ADMIN'), ('manager', 'MANAGER'), ('waiter01', 'WAITER'),
    ('kitchen01', 'KITCHEN'), ('cashier01', 'CASHIER'),
    ('warehouse', 'WAREHOUSE'), ('analyst01', 'DATA_ANALYST')
) AS mapping(username, role_code)
JOIN users u ON u.username = mapping.username
JOIN roles r ON r.role_code = mapping.role_code
CROSS JOIN users a
WHERE a.username = 'admin'
ON CONFLICT (user_id, role_id) DO NOTHING;

-- Quyền ADMIN: toàn bộ quyền.
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.role_id, p.permission_id
FROM roles r CROSS JOIN permissions p
WHERE r.role_code = 'ADMIN'
ON CONFLICT (role_id, permission_id) DO NOTHING;

-- Quyền theo từng vai trò nghiệp vụ.
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.role_id, p.permission_id
FROM (VALUES
    ('MANAGER', 'MENU_MANAGE'), ('MANAGER', 'RECIPE_MANAGE'),
    ('MANAGER', 'TABLE_MANAGE'), ('MANAGER', 'PURCHASE_APPROVE'),
    ('MANAGER', 'PROPOSAL_REVIEW'), ('MANAGER', 'REPORT_VIEW'),
    ('WAITER', 'TABLE_MANAGE'), ('WAITER', 'ORDER_CREATE'),
    ('KITCHEN', 'KITCHEN_PROCESS'),
    ('CASHIER', 'PAYMENT_CREATE'), ('CASHIER', 'REPORT_VIEW'),
    ('WAREHOUSE', 'INVENTORY_MANAGE'), ('WAREHOUSE', 'PURCHASE_MANAGE'),
    ('DATA_ANALYST', 'FORECAST_RUN'), ('DATA_ANALYST', 'REPORT_VIEW')
) AS mapping(role_code, permission_code)
JOIN roles r ON r.role_code = mapping.role_code
JOIN permissions p ON p.permission_code = mapping.permission_code
ON CONFLICT (role_id, permission_id) DO NOTHING;

INSERT INTO units (unit_code, unit_name, dimension) VALUES
    ('G',   'Gram',      'MASS'),
    ('KG',  'Kilogram',  'MASS'),
    ('ML',  'Millilít',  'VOLUME'),
    ('L',   'Lít',       'VOLUME'),
    ('PCS', 'Cái/Phần',  'COUNT')
ON CONFLICT (unit_code) DO NOTHING;

INSERT INTO unit_conversions (from_unit_id, to_unit_id, factor)
SELECT f.unit_id, t.unit_id, x.factor
FROM (VALUES ('KG', 'G', 1000.000000::numeric),
             ('L', 'ML', 1000.000000::numeric)) AS x(from_code, to_code, factor)
JOIN units f ON f.unit_code = x.from_code
JOIN units t ON t.unit_code = x.to_code
ON CONFLICT (from_unit_id, to_unit_id) DO NOTHING;

INSERT INTO ingredients
    (ingredient_code, ingredient_name, base_unit_id, manages_lot,
     default_shelf_life_days, minimum_stock_qty, safety_stock_qty)
SELECT x.code, x.name, u.unit_id, x.manages_lot, x.shelf_life, x.min_qty, x.safety_qty
FROM (VALUES
    ('RICE',       'Gạo',          'G',  true,  180, 10000.000, 5000.000),
    ('CHICKEN',    'Thịt gà',      'G',  true,    3,  5000.000, 2500.000),
    ('BEEF',       'Thịt bò',      'G',  true,    3,  5000.000, 2500.000),
    ('NOODLE',     'Bánh phở',     'G',  true,    2,  3000.000, 1500.000),
    ('FISH_SAUCE', 'Nước mắm',     'ML', true,  365,  2000.000, 1000.000),
    ('TEA',        'Trà',          'G',  true,  365,   500.000,  200.000),
    ('PEACH',      'Đào ngâm',     'G',  true,   30,  1000.000,  500.000)
) AS x(code, name, unit_code, manages_lot, shelf_life, min_qty, safety_qty)
JOIN units u ON u.unit_code = x.unit_code
ON CONFLICT (ingredient_code) DO NOTHING;

INSERT INTO dining_tables (table_code, table_name, capacity) VALUES
    ('A01', 'Bàn A01', 4), ('A02', 'Bàn A02', 4),
    ('A03', 'Bàn A03', 6), ('B01', 'Bàn B01', 2), ('B02', 'Bàn B02', 8)
ON CONFLICT (table_code) DO NOTHING;

INSERT INTO menu_categories
    (category_code, category_name, description, display_order) VALUES
    ('MAIN',  'Món chính', 'Các món ăn chính', 1),
    ('DRINK', 'Đồ uống',   'Nước giải khát',   2)
ON CONFLICT (category_code) DO NOTHING;

INSERT INTO dishes (dish_code, dish_name, category_id, selling_price, description)
SELECT x.code, x.name, c.category_id, x.price, x.description
FROM (VALUES
    ('COM_GA',  'Cơm gà nướng',  'MAIN',  65000.00, 'Cơm gà nướng dùng kèm nước mắm'),
    ('PHO_BO',  'Phở bò',        'MAIN',  70000.00, 'Phở bò truyền thống'),
    ('TRA_DAO', 'Trà đào',       'DRINK', 35000.00, 'Trà đào lạnh')
) AS x(code, name, category_code, price, description)
JOIN menu_categories c ON c.category_code = x.category_code
ON CONFLICT (dish_code) DO NOTHING;

INSERT INTO recipe_versions
    (dish_id, version_no, status, effective_from, created_by, notes)
SELECT d.dish_id, 1, 'ACTIVE', DATE '2026-08-01', u.user_id, 'Công thức mẫu phiên bản 1'
FROM dishes d CROSS JOIN users u
WHERE d.dish_code IN ('COM_GA', 'PHO_BO', 'TRA_DAO')
  AND u.username = 'manager'
ON CONFLICT (dish_id, version_no) DO NOTHING;

INSERT INTO recipe_items
    (recipe_version_id, ingredient_id, quantity, unit_id, base_quantity)
SELECT rv.recipe_version_id, i.ingredient_id, x.qty, unit_used.unit_id, x.base_qty
FROM (VALUES
    ('COM_GA',  'RICE',       'G',  200.000, 200.000),
    ('COM_GA',  'CHICKEN',    'G',  250.000, 250.000),
    ('COM_GA',  'FISH_SAUCE', 'ML',  20.000,  20.000),
    ('PHO_BO',  'BEEF',       'G',  180.000, 180.000),
    ('PHO_BO',  'NOODLE',     'G',  250.000, 250.000),
    ('PHO_BO',  'FISH_SAUCE', 'ML',  15.000,  15.000),
    ('TRA_DAO', 'TEA',        'G',   10.000,  10.000),
    ('TRA_DAO', 'PEACH',      'G',   80.000,  80.000)
) AS x(dish_code, ingredient_code, unit_code, qty, base_qty)
JOIN dishes d ON d.dish_code = x.dish_code
JOIN recipe_versions rv ON rv.dish_id = d.dish_id AND rv.version_no = 1
JOIN ingredients i ON i.ingredient_code = x.ingredient_code
JOIN units unit_used ON unit_used.unit_code = x.unit_code
ON CONFLICT (recipe_version_id, ingredient_id) DO NOTHING;

INSERT INTO suppliers
    (supplier_code, supplier_name, contact_name, phone, email, address, tax_code) VALUES
    ('NCC_FRESH', 'Thực phẩm Tươi Sài Gòn', 'Nguyễn Văn An', '0909000001',
     'sales@fresh.local', 'Quận 7, TP.HCM', '0312345678'),
    ('NCC_DRY', 'Nông sản Miền Tây', 'Trần Thị Bình', '0909000002',
     'sales@dry.local', 'Cần Thơ', '1801234567')
ON CONFLICT (supplier_code) DO NOTHING;

INSERT INTO supplier_ingredients
    (supplier_id, ingredient_id, supplier_sku, purchase_unit_id,
     base_qty_per_purchase_unit, lead_time_days, minimum_order_qty,
     latest_unit_price, is_preferred)
SELECT s.supplier_id, i.ingredient_id, x.sku, u.unit_id, x.base_qty,
       x.lead_days, x.min_order, x.price, true
FROM (VALUES
    ('NCC_DRY',   'RICE',    'GAO-5KG', 'KG', 1000.000, 2, 5.000,  22000.00),
    ('NCC_FRESH', 'CHICKEN', 'GA-1KG',  'KG', 1000.000, 1, 5.000,  85000.00),
    ('NCC_FRESH', 'BEEF',    'BO-1KG',  'KG', 1000.000, 1, 3.000, 210000.00),
    ('NCC_FRESH', 'NOODLE',  'PHO-1KG', 'KG', 1000.000, 1, 3.000,  30000.00)
) AS x(supplier_code, ingredient_code, sku, unit_code,
       base_qty, lead_days, min_order, price)
JOIN suppliers s ON s.supplier_code = x.supplier_code
JOIN ingredients i ON i.ingredient_code = x.ingredient_code
JOIN units u ON u.unit_code = x.unit_code
ON CONFLICT (supplier_id, ingredient_id) DO NOTHING;

INSERT INTO model_versions
    (model_name, algorithm, version_label, parameters, feature_config,
     trained_at, training_data_from, training_data_to, status, created_by, notes)
SELECT 'restaurant_demand_forecast', 'XGBoost', 'v1.0',
       '{"n_estimators":200,"max_depth":6,"learning_rate":0.05}'::jsonb,
       '{"features":["day_of_week","lag_7","rolling_mean_7"]}'::jsonb,
       TIMESTAMPTZ '2026-08-20 09:00:00+07', DATE '2026-01-01', DATE '2026-07-31',
       'ACTIVE', u.user_id, 'Model mẫu dùng cho đồ án'
FROM users u WHERE u.username = 'analyst01'
ON CONFLICT (model_name, version_label) DO NOTHING;

INSERT INTO model_metrics
    (model_version_id, metric_name, metric_value, dataset_scope)
SELECT mv.model_version_id, x.metric_name, x.metric_value, 'TEST'
FROM model_versions mv
CROSS JOIN (VALUES ('MAE', 2.350000::numeric),
                   ('RMSE', 3.120000::numeric),
                   ('MAPE', 8.740000::numeric)) AS x(metric_name, metric_value)
WHERE mv.model_name = 'restaurant_demand_forecast' AND mv.version_label = 'v1.0'
ON CONFLICT (model_version_id, metric_name, dataset_scope) DO NOTHING;

INSERT INTO forecast_runs
    (model_version_id, forecast_start_date, forecast_end_date, horizon_days,
     trigger_type, status, generated_by, generated_at)
SELECT mv.model_version_id, DATE '2026-08-28', DATE '2026-09-03', 7,
       'MANUAL', 'COMPLETED', u.user_id, TIMESTAMPTZ '2026-08-27 10:00:00+07'
FROM model_versions mv CROSS JOIN users u
WHERE mv.model_name = 'restaurant_demand_forecast' AND mv.version_label = 'v1.0'
  AND u.username = 'analyst01'
  AND NOT EXISTS (
      SELECT 1 FROM forecast_runs fr
      WHERE fr.model_version_id = mv.model_version_id
        AND fr.forecast_start_date = DATE '2026-08-28'
        AND fr.forecast_end_date = DATE '2026-09-03'
  );

INSERT INTO forecast_results
    (forecast_run_id, dish_id, forecast_date, predicted_qty, lower_bound, upper_bound)
SELECT fr.forecast_run_id, d.dish_id, x.forecast_date, x.predicted_qty,
       x.lower_bound, x.upper_bound
FROM (VALUES
    ('COM_GA',  DATE '2026-08-28', 35.000, 30.000, 40.000),
    ('PHO_BO',  DATE '2026-08-28', 28.000, 24.000, 33.000),
    ('TRA_DAO', DATE '2026-08-28', 42.000, 36.000, 49.000)
) AS x(dish_code, forecast_date, predicted_qty, lower_bound, upper_bound)
JOIN dishes d ON d.dish_code = x.dish_code
JOIN forecast_runs fr
  ON fr.forecast_start_date = DATE '2026-08-28'
 AND fr.forecast_end_date = DATE '2026-09-03'
ON CONFLICT (forecast_run_id, dish_id, forecast_date) DO NOTHING;

INSERT INTO replenishment_proposals
    (proposal_number, forecast_run_id, planning_start_date, planning_end_date,
     status, reviewed_by, reviewed_at, decision_reason)
SELECT 'DXNH-20260827-001', fr.forecast_run_id,
       DATE '2026-08-28', DATE '2026-09-03', 'APPROVED',
       u.user_id, TIMESTAMPTZ '2026-08-27 11:00:00+07', 'Đồng ý nhập theo đề xuất'
FROM forecast_runs fr CROSS JOIN users u
WHERE fr.forecast_start_date = DATE '2026-08-28'
  AND fr.forecast_end_date = DATE '2026-09-03'
  AND u.username = 'manager'
ON CONFLICT (proposal_number) DO NOTHING;

INSERT INTO replenishment_proposal_items
    (proposal_id, ingredient_id, forecast_demand_qty, available_stock_qty,
     incoming_qty, safety_stock_qty, lead_time_days_snapshot, suggested_qty,
     adjusted_qty, preferred_supplier_id, adjustment_reason)
SELECT rp.proposal_id, i.ingredient_id, x.demand_qty, x.available_qty,
       0, i.safety_stock_qty, x.lead_days, x.suggested_qty,
       x.adjusted_qty, s.supplier_id, x.reason
FROM (VALUES
    ('CHICKEN', 'NCC_FRESH', 8750.000, 3000.000, 1, 8250.000, 9000.000, 'Làm tròn theo đơn vị kg'),
    ('RICE',    'NCC_DRY',   7000.000, 2000.000, 2, 10000.000, 10000.000, 'Đủ mức đặt tối thiểu')
) AS x(ingredient_code, supplier_code, demand_qty, available_qty,
       lead_days, suggested_qty, adjusted_qty, reason)
JOIN replenishment_proposals rp ON rp.proposal_number = 'DXNH-20260827-001'
JOIN ingredients i ON i.ingredient_code = x.ingredient_code
JOIN suppliers s ON s.supplier_code = x.supplier_code
ON CONFLICT (proposal_id, ingredient_id) DO NOTHING;

INSERT INTO purchase_orders
    (purchase_order_number, supplier_id, proposal_id, status, order_date,
     expected_delivery_date, created_by, approved_by, subtotal_amount, notes)
SELECT 'PO-20260827-001', s.supplier_id, rp.proposal_id, 'RECEIVED',
       DATE '2026-08-27', DATE '2026-08-28', creator.user_id,
       approver.user_id, 765000.00, 'Đơn mua mẫu từ đề xuất AI'
FROM suppliers s
JOIN replenishment_proposals rp ON rp.proposal_number = 'DXNH-20260827-001'
CROSS JOIN users creator
CROSS JOIN users approver
WHERE s.supplier_code = 'NCC_FRESH'
  AND creator.username = 'warehouse'
  AND approver.username = 'manager'
ON CONFLICT (purchase_order_number) DO NOTHING;

INSERT INTO purchase_order_items
    (purchase_order_id, supplier_ingredient_id, purchase_unit_id,
     ordered_quantity, base_qty_per_purchase_unit, expected_unit_price)
SELECT po.purchase_order_id, si.supplier_ingredient_id, si.purchase_unit_id,
       9.000, si.base_qty_per_purchase_unit, 85000.00
FROM purchase_orders po
JOIN supplier_ingredients si ON si.supplier_id = po.supplier_id
JOIN ingredients i ON i.ingredient_id = si.ingredient_id
WHERE po.purchase_order_number = 'PO-20260827-001'
  AND i.ingredient_code = 'CHICKEN'
ON CONFLICT (purchase_order_id, supplier_ingredient_id) DO NOTHING;

INSERT INTO goods_receipts
    (receipt_number, purchase_order_id, receipt_date, supplier_document_no,
     status, received_by, notes)
SELECT 'GR-20260828-001', po.purchase_order_id, DATE '2026-08-28',
       'HD-FRESH-001', 'CONFIRMED', u.user_id, 'Nhập đủ số lượng đặt hàng'
FROM purchase_orders po CROSS JOIN users u
WHERE po.purchase_order_number = 'PO-20260827-001'
  AND u.username = 'warehouse'
ON CONFLICT (receipt_number) DO NOTHING;

INSERT INTO goods_receipt_items
    (goods_receipt_id, purchase_order_item_id, received_quantity,
     purchase_unit_id, base_quantity, actual_unit_price,
     lot_code, manufacture_date, expiry_date)
SELECT gr.goods_receipt_id, poi.purchase_order_item_id, 9.000,
       poi.purchase_unit_id, 9000.000, 85000.00,
       'GA-20260828-A', DATE '2026-08-28', DATE '2026-08-31'
FROM goods_receipts gr
JOIN purchase_order_items poi ON poi.purchase_order_id = gr.purchase_order_id
JOIN supplier_ingredients si
  ON si.supplier_ingredient_id = poi.supplier_ingredient_id
JOIN ingredients i ON i.ingredient_id = si.ingredient_id
WHERE gr.receipt_number = 'GR-20260828-001'
  AND i.ingredient_code = 'CHICKEN'
  AND NOT EXISTS (
      SELECT 1 FROM goods_receipt_items gri
      WHERE gri.goods_receipt_id = gr.goods_receipt_id
        AND gri.purchase_order_item_id = poi.purchase_order_item_id
  );

INSERT INTO stock_lots
    (ingredient_id, goods_receipt_item_id, lot_code, manufacture_date,
     expiry_date, received_quantity, current_quantity, unit_cost, status)
SELECT i.ingredient_id, gri.goods_receipt_item_id, gri.lot_code,
       gri.manufacture_date, gri.expiry_date, gri.base_quantity,
       gri.base_quantity,
       (gri.received_quantity * gri.actual_unit_price) / gri.base_quantity,
       'ACTIVE'
FROM goods_receipt_items gri
JOIN purchase_order_items poi
  ON poi.purchase_order_item_id = gri.purchase_order_item_id
JOIN supplier_ingredients si
  ON si.supplier_ingredient_id = poi.supplier_ingredient_id
JOIN ingredients i ON i.ingredient_id = si.ingredient_id
WHERE gri.lot_code = 'GA-20260828-A'
ON CONFLICT (ingredient_id, lot_code) DO NOTHING;

INSERT INTO stock_movements
    (movement_number, ingredient_id, stock_lot_id, movement_type, direction,
     quantity, occurred_at, performed_by, goods_receipt_item_id, reason)
SELECT 'SM-IN-20260828-001', sl.ingredient_id, sl.stock_lot_id,
       'RECEIPT', 'IN', sl.received_quantity,
       TIMESTAMPTZ '2026-08-28 08:30:00+07', u.user_id,
       sl.goods_receipt_item_id, 'Nhập kho theo phiếu GR-20260828-001'
FROM stock_lots sl CROSS JOIN users u
WHERE sl.lot_code = 'GA-20260828-A'
  AND u.username = 'warehouse'
  AND NOT EXISTS (
      SELECT 1 FROM stock_movements sm
      WHERE sm.movement_number = 'SM-IN-20260828-001'
  );

INSERT INTO orders
    (order_number, table_id, opened_by, status, opened_at, sent_at,
     completed_at, subtotal_amount, notes)
SELECT 'ORD-20260828-001', t.table_id, u.user_id, 'PAID',
       TIMESTAMPTZ '2026-08-28 12:00:00+07',
       TIMESTAMPTZ '2026-08-28 12:05:00+07',
       TIMESTAMPTZ '2026-08-28 12:25:00+07',
       130000.00, 'Order dữ liệu mẫu'
FROM dining_tables t CROSS JOIN users u
WHERE t.table_code = 'A01' AND u.username = 'waiter01'
ON CONFLICT (order_number) DO NOTHING;

INSERT INTO order_items
    (order_id, dish_id, recipe_version_id, quantity, unit_price,
     status, sent_at, completed_at)
SELECT o.order_id, d.dish_id, rv.recipe_version_id, 2, d.selling_price,
       'COMPLETED', TIMESTAMPTZ '2026-08-28 12:05:00+07',
       TIMESTAMPTZ '2026-08-28 12:25:00+07'
FROM orders o
JOIN dishes d ON d.dish_code = 'COM_GA'
JOIN recipe_versions rv ON rv.dish_id = d.dish_id AND rv.status = 'ACTIVE'
WHERE o.order_number = 'ORD-20260828-001'
  AND NOT EXISTS (
      SELECT 1 FROM order_items oi
      WHERE oi.order_id = o.order_id AND oi.dish_id = d.dish_id
  );

INSERT INTO payments
    (payment_number, order_id, amount, payment_method, received_by, paid_at, notes)
SELECT 'PAY-20260828-001', o.order_id, o.subtotal_amount,
       'CASH', u.user_id, TIMESTAMPTZ '2026-08-28 12:30:00+07', 'Thanh toán mẫu'
FROM orders o CROSS JOIN users u
WHERE o.order_number = 'ORD-20260828-001' AND u.username = 'cashier01'
ON CONFLICT (payment_number) DO NOTHING;

INSERT INTO audit_logs
    (actor_user_id, action_code, entity_type, entity_id,
     description, new_values, ip_address)
SELECT u.user_id, 'DATABASE_SEEDED', 'SYSTEM', 'restaurant_ai',
       'Khởi tạo dữ liệu mẫu cho đồ án',
       '{"source":"restaurant_ai_database.sql","demo":true}'::jsonb,
       '127.0.0.1'::inet
FROM users u
WHERE u.username = 'admin'
  AND NOT EXISTS (
      SELECT 1 FROM audit_logs al
      WHERE al.action_code = 'DATABASE_SEEDED'
        AND al.entity_id = 'restaurant_ai'
  );

COMMIT;

-- =============================================================================
-- 10. CÂU LỆNH KIỂM TRA SAU KHI CHẠY
-- =============================================================================

SELECT count(*) AS total_tables
FROM information_schema.tables
WHERE table_schema = 'restaurant_ai' AND table_type = 'BASE TABLE';

SELECT table_name
FROM information_schema.tables
WHERE table_schema = 'restaurant_ai' AND table_type = 'BASE TABLE'
ORDER BY table_name;
